---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: n8n
  namespace: argocd
spec:
  project: payload
  source:
    # repoURL: oci://8gears.container-registry.com/library/n8n
    # chart: n8n
    # targetRevision: "0.23.0"

    repoURL: https://github.com/8gears/n8n-helm-chart.git
    targetRevision: 1.0.6 # appVersion: 1.85.1
    path: ./charts/n8n

    helm:
      releaseName: n8n
      values: |
        image:
          repository: n8nio/n8n
          tag: 1.85.1

        extraEnv:
          WEBHOOK_URL: https://n8n.agrrh.com/
          NODE_FUNCTION_ALLOW_EXTERNAL: lodash
          TZ: Europe/Moscow

        config:
          database:
            type: postgresdb

        # FIXME Store password in secure manner
        n8n:
          encryption_key: MyEncryptionKey1

        # FIXME Store password in secure manner
        secret:
          database:
            postgresdb:
              host: postgres.n8n.svc
              user: n8n
              password: n8nQwertyPass
              database: n8n

        persistence:
          enabled: true
          type: dynamic
          storageClass: microk8s-hostpath
          accessModes:
            - ReadWriteOnce
          size: 5Gi

  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
