---

apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: dockerhub
  labels:
    app: dockerhub-proxy
spec:
  selector:
    app: dockerhub-proxy
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 5000
