---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: request-headers
  namespace: kube-system

spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: whitelist
  namespace: kube-system

spec:
  ipWhiteList:
    sourceRange:
      - 10.0.40.0/24        # vpn
      - 10.0.55.0/24        # lan
      - 178.170.198.0/24    # home
      - 10.43.0.0/16
      - 10.42.0.0/16
      # Telegram
      - 149.154.160.0/20
      - 91.108.4.0/22
    ipStrategy:
      excludedIPs:
        - 10.0.55.201/32    # kube1
        - 84.38.180.136/32  # gw1
        - 10.0.40.11/24
        - 31.184.254.89/32  # gw2
        - 10.0.40.21/24
        - 10.0.55.1/32      # home router
        - 10.43.0.0/16      # k8s service
        - 10.42.0.0/16      # k8s pods
