---

apiVersion: v1
kind: Service

metadata:
  name: traefik-nodeport
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik

spec:
  type: NodePort

  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik

  externalTrafficPolicy: Local
  internalTrafficPolicy: Local

  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

  ports:
    - name: web
      nodePort: 32080
      port: 80
      protocol: TCP
      targetPort: web
    - name: websecure
      nodePort: 32443
      port: 443
      protocol: TCP
      targetPort: websecure

  sessionAffinity: None

status:
  loadBalancer: {}
