---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: argocd
  namespace: argocd

spec:
  project: default

  destination:
    name: brave-booth
    namespace: argocd

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 6.11.1

      helm:
        valueFiles:
          - $values/kubernetes-v2/argocd/values.yaml

    - repoURL: https://github.com/agrrh/infrastructure
      targetRevision: HEAD
      ref: values

  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true
