---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: binance-bot-logs
  namespace: crypto-stuff
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: binance-bot-data
  namespace: crypto-stuff
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
