# NOTE Loki: like Prometheus, but for logs.
#   https://grafana.github.io/loki/charts/

---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: loki
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "4.7.0"
    helm:
      # https://github.com/grafana/loki/blob/v2.5.0/production/helm/loki/values.yaml
      values: |
        ---
        ingress:
          enabled: false

        loki:
          auth_enabled: false

          commonConfig:
            replication_factor: 1

          storage:
            type: filesystem

        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 10Gi
          storageClassName: microk8s-hostpath

        # write:
        #   replicas: 1
        #
        # read:
        #   replicas: 1
        #
        # backend:
        #   replicas: 1

        singleBinary:
          replicas: 1

  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  ignoreDifferences:
    - group: apps/v1
      kind: StatefulSet
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.persistentVolumeClaimRetentionPolicy.whenDeleted
        - .spec.persistentVolumeClaimRetentionPolicy.whenScaled
