---

apiVersion: v1
kind: ConfigMap
metadata:
  name: controller
  namespace: meta-project
data:
  sync.py: |
    from http.server import BaseHTTPRequestHandler, HTTPServer
    import json

    class Controller(BaseHTTPRequestHandler):
      def sync(self, parent, children):
        # Compute status based on observed state.
        print(children["Namespace.v1"])

        desired_status = {
          "namespaces": hash(children["Namespace.v1"])
        }

        # Generate the desired child object(s).
        description = parent.get("spec", {}).get("description", "")
        license = parent.get("spec", {}).get("license", "WTFPL")

        desired_namespaces = [
          {
            "apiVersion": "v1",
            "kind": "Namespace",
            "metadata": {
              "name": "-".join("proj", parent["metadata"]["name"]),
              "annotations": {
                "description": parent["spec"]["description"],
                "license": parent["spec"]["license"],
              }
            }
          }
        ]

        return {"status": desired_status, "children": desired_namespaces}

      def do_POST(self):
        # Serve the sync() function as a JSON webhook.
        observed = json.loads(self.rfile.read(int(self.headers.get("content-length"))))
        desired = self.sync(observed["parent"], observed["children"])

        self.send_response(200)
        self.send_header("Content-type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(desired).encode())

    HTTPServer(("", 80), Controller).serve_forever()
