---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.agrrh.com
spec:
  group: agrrh.com
  names:
    kind: Project
    plural: projects
    singular: projects
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                description:
                  type: string
                license:
                  type: string
      subresources:
        status: {}
