---

kind: pipeline
type: kubernetes
name: backup-commento

volumes:
  - name: commento-dump
    temp: {}

steps:
  - name: pgsql-dump
    image: postgres:15.1
    volumes:
      - name: commento-dump
        path: /var/tmp/dump
    environment:
      DB_HOSTNAME:
        from_secret: commento_postgres_hostname
      DB_USERNAME:
        from_secret: commento_postgres_username
      DB_PASSWORD:
        from_secret: commento_postgres_password
      DB_DATABASE:
        from_secret: commento_postgres_database
    commands:
      - >
        pg_dump \
          postgresql://$${DB_USERNAME}:$${DB_PASSWORD}@$${DB_HOSTNAME}:5432/$${DB_DATABASE} \
          > /var/tmp/dump/dump.sql

  - name: compress-data
    image: agrrh/cider:0.3.0
    volumes:
      - name: commento-dump
        path: /var/tmp/dump
    commands:
      - pigz --best /var/tmp/dump/dump.sql

  - name: audit
    image: alpine:3.17
    volumes:
      - name: commento-dump
        path: /var/tmp/dump
    commands:
      - cd /var/tmp/dump
      - zcat dump.sql.gz | head
      - stat dump.sql.gz

trigger:
  event:
    - cron
    - custom
  ref:
    - refs/heads/master
