---

kind: template
load: backups.yaml
data:
  profiles:
    - name: commento
      namespace: drone
      postgres:
        - name: commento
      mysql: []
      files: []

    - name: n8n
      namespace: drone
      postgres:
        - name: commento
      mysql: []
      files: []

    - name: passbolt
      namespace: passbolt
      postgres: []
      mysql:
        - name: passbolt
      files:
        - name: passbolt
          claim: passbolt
          subpath: gpg/
