---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tg-personal-assistant-dev
  namespace: argocd
spec:
  project: payload
  source:
    repoURL: https://github.com/agrrh/tg-personal-assistant
    targetRevision: master
    path: kubernetes/dev
    directory:
      recurse: true
  destination:
    namespace: tg-personal-assistant-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - >-
          select(.metadata.annotations | select(.["keel.sh/policy"] != null))
          | .spec.template.spec.initContainers[]?.image
        - >-
          select(.metadata.annotations | select(.["keel.sh/policy"] != null))
          | .spec.template.spec.containers[].image
