apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tg-token
  namespace: tg-steps-challenge-dev
spec:
  encryptedData:
    token: AgCV65SlDukGU4Lzfb8RaftNONqwbbHEtFoN0M0phFD307ujP6pHu1zdkZduXylJ9f5MRe43ySOSd04KzYO9FLuWC0ffwQPI1kq90twgBgOMa+GQGADuXQiJevPsIzB5vE/TBf8rbZqCV7sJuMb48O13FVXXZDDwOXMxtEH2WFEaNRMXMgMH1Cbud/CqsNemuaAMefcxb/BZckhgW/F3W5nBCWanjra6IjDE1jXOw4gn14dgxuvdEDbemp5HI5BCUSt+ZlCV47rQcbGsny2ntXreSadHDTQFRtcCfv7+7EsPAtcCpxHVv48VSrtEWL9Kblm9BNAD3q7deGLkoTpfm9xXpcG+ea+v9Tpm/eWg2f5AyZIeEdBBvSNkkrYu6+b9o1RLi3KhpaoWXZWRQntiunllOuE3IeJ/wlQR1l4ux1ECOz7OHsSJGuMQiXEwPQsNkebF3fYWeEoe9l5QjOBSbhpLSDOiBlxDzZT9DQxKFDG/ZCwbYufvEXQYkgd27R7+Imv2zYbeZ6SBWwVo60raHYyMDJAh+tejEqfH2zYa/dHNUh9j88IxW31ytCWwJfostZXTA6W4VdTqz/OAc0ugjBd62yxqAOTuko7+xP6aKWWooYzb2A3owmyPQ99xHuKP3X+o5qMWcUr72n3Ozp1ctiAX/GSJLgjDAOgorG6SwQ9hrXhiZ1FIn6jI489nwRQ5FU69ryxjezcuIMKCKHCUg7h2bZVZxcUw3RoQ4vfkLjjhKYEm4RBQpac/z3Rf3nTk
  template:
    metadata:
      creationTimestamp: null
      name: tg-token
      namespace: tg-steps-challenge-dev

