---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: events-bus
  namespace: bus
spec:
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts
    chart: nats
    targetRevision: 0.18.0

    helm:
      values: |
        fullnameOverride: "nats"

  destination:
    namespace: bus
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
