---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin
  namespace: kargo
spec:
  encryptedData:
    ADMIN_ACCOUNT_PASSWORD_HASH: AgDfst6BNCberCeF00np2owab4Zwa40yy9ClK/252R1ar3llggLHYLGar5EkSGunPJvtjPyvs4uMY252r8IjfzRr32dgZAzUsMYnTGeSQV+WM+p6EGfX2aALSHISd0FvCoIL9VWuMHrsumAcaEx3A1SHHVJye4emi1lxxbV9dYk4Zc8Rm6qQhrvwsnXJlaz3EN2pmUQXNpB/47JpFRwMrRJLrV8CADMMAupGteJkU/QdYCtGmPYeLFrUzkOYo+NjCEFid90j/6S12Vq7xRZkKgEVLxssGm3oE+QZvY8E8iyRs4RM/C9ypmETa5ODjxt4JK4dv3UrI8Oia4qCPvSTNf1SRvf4bQbH/a9kz8xMl/vySCkRFnyq6tPOFUSijDtkG7YR8W4h+71EkSb8PEIYJCzWZqm1uZhNZOloqQZtDFOm7AaXiMsABAdVWLwNUA12RuysGq7hU2LDAZ8/aFwx8rHcVyZzXVmyF8MAgU5xKaBcsc5xSgA/z/HoUDTs3UZ5d76oFXlyuFhYFD5+R4XnTE3kwGjpLgflFp6oFdHlb+iniaDDvjZ/EzhK9YzPtaqbUNIifTatm3LANZO+r2/S6F48eRccuI5u2Oufswi7cKBKgm3582+Kr4JvogGTnfa/uHJtIrG2VwNfSXk0Meg7aunzDUMQX3LJoR2svkgxScJqEdt0B65d/wg5Jon1VVRDCKOLhNS2fbYLwBwxrmEzDqeZg0JGEVubwId8mR2jZE0X+E7+C8AEZ4SBW+30Eo/11wWJe91g6lHTc9UqDvM=
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: AgAdRJEO7DskKd2VxW4kgQIJO1Y7454WcOerQUq/Fu37J8ESwzUKTugWbOmcE4bknzsOk6t2KpJ95DSp//lKIjzJT9i+bVg+emew9pAmQnx1jOiYnt14YGE1BZQhC8tmJJneJqAw3E5z7BI8LlQ4N9k4SaDGDN1LA18Zk2IFe2KrjH2gzAEO+Ja6DoA89U7m0B5RGjUfrYb38pRQtjMONrEa6NfA8ObCe2zVPuxR/BCWxgxKiMiHdz2VQxVvEq2TWiPZghiH5Soyt1xwloOJMgUZ7lxZ4mZQNPJANrC/7Y6s728PbPMVf6l8mJTWKRR75OZi2xJjYcXhstDdhOfSg+a/SkmHfJIt9isztu809VLiBlXowI2ATXfkbMBuYziClb6HP1z6tHomXy9gM6K7K6pYHAq9Zfn+glmuCvI+N36WU1Vk3TVNuecT7JB3QvM9/prJi/x2o9ri+79YwrYt8ovH14aL3mh3gXuwjNhbUIUV3eAVpCMXJFHcMn3H+1vAK9Kj+PeucZruv3Be4+t3T79ciyI6L29fE+TQVbTBtuV1Ze4gcjs32Gwj3pb2NhlM0OncwuZZt6N7DKsC4Q8rTHlGFUueOsgi00woppNLlJmS22HPttrLq5f/3DEfkiKQLHmTIQJQl/LVOkpH+dUtz5lCDgu70Dsb9FNdK4A5VHRR4xVNL3stp2aiagX5rwonXfGCfIHRo6rOFgh4+7lbIRF3cmA2m6tiJeENTSU5adz5qQ==
  template:
    metadata:
      creationTimestamp: null
      name: admin
      namespace: kargo
