---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-argocd
  namespace: argocd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - '*'
