---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tg-step-counter-nats-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts/nats
    chart: nats
    targetRevision: 0.18.0

    helm:
      values: |
        # nothing

  destination:
    namespace: tg-step-counter-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
