{{ range .input.targets }}
---

kind: pipeline
type: kubernetes
name: backup-{{ .name }}

clone:
  disable: true

volumes:
  - name: data
    temp: {}

steps:
  - name: {{ .name }}-dump
    image: postgres:15.1
    depends_on: []
    volumes:
      - name: data
        path: /data
    environment:
      DB_HOSTNAME:
        from_secret: {{ .name }}_postgres_hostname
      DB_USERNAME:
        from_secret: {{ .name }}_postgres_username
      DB_PASSWORD:
        from_secret: {{ .name }}_postgres_password
      DB_DATABASE:
        from_secret: {{ .name }}_postgres_database
    commands:
      - >
        pg_dump \
          postgresql://$${DB_USERNAME}:$${DB_PASSWORD}@$${DB_HOSTNAME}:5432/$${DB_DATABASE} \
          > /data/dump.sql

  # TODO: notify size somewhere to perform sanity check?
  - name: audit
    image: alpine:3.17
    volumes:
      - name: data
        path: /data
    commands:
      - cd /data
      - ls -lh ./

  # NOTE: To evade concurrency
  - name: delay
    image: alpine:3.17
    commands:
      - sleep {{ .delay }}

  - name: upload-data
    image: agrrh/cider:0.4.0
    environment:
      RESTIC_REPOSITORY: "rclone:yandex:/backups"
      RESTIC_PASSWORD:
        from_secret: restic_password
      RCLONE_CONFIG_BODY:
        from_secret: rclone_yandex_config
    volumes:
      - name: data
        path: /data
    commands:
      # Prepare Rclone profile
      - mkdir -p ~/.config/rclone
      - echo $${RCLONE_CONFIG_BODY} | base64 -d > ~/.config/rclone/rclone.conf
      - rclone size yandex:/

      # Actually upload
      - cd /data
      - >
        restic \
          backup \
          --host drone \
          --tag sql,{{ .name }} \
          ./

      - >
        restic \
          forget \
          --host drone \
          --tag sql,{{ .name }} \
          --keep-daily 7 \
          --keep-weekly 4 \
          --keep-monthly 12 \
          --keep-yearly 10 \
          --prune

      - >
        restic \
          snapshots \
          --host drone

trigger:
  event:
    - cron
    - custom
  ref:
    - refs/heads/master

{{ end }}
