---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: commento-http
  namespace: commento

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`commento.agrrh.com`) || Host(`commento.5426b488.nip.io`)
      middlewares:
        - name: request-headers
          namespace: traefik
      services:
        - kind: Service
          name: commento
          namespace: commento
          port: 80
