apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth-github
  namespace: commento
spec:
  encryptedData:
    key: AgCNfR3jKbVFFYZBQXgpYRTYSpm4rk6QBxyp3m0/n42jiwIHfqsZaQi/McWd8OcX83QqkROmoHADXEn5e67v+tfaCkvguc7pnYgk4QNBBkL0Q4HGz8y8f75z1pAlRnplNwMaQT4CBP7RW8HRW/9G28VBR+ylFUEFCBX5+zmSmjFTZ15was9dvm5cpzPKFLYSoHxlm2O595br/tsxRhDfCwFSJ/xvc3BRRA6rOGiwx/WzNf9WlKQGfkvudBie/YojTOmrPcBW1KEwJWyKsQEOJAoDV9baV9TirGKLEnMjG8gAH/wrNkFk7JrmGhUloHTKmA/qUfuRrWMHDIrPIueO4BkWAhJArAnyqQp6/dpc1SLbuU7ipj9966fM/nZvWibntwTR4pMAccelhdtzPLXqquc7cvOg+dPnQBpZCY95mL5OckgrxBa4hM7lwmAq89O0LZXDv1jAkTMcnEXrhtglxYADlBc6pHhzS9BzN+ceT0afIv5P8jhWfu8VVLNjuPlUhdPrMtX7M4y7ALw8tnVWKiDav5wLCR25U5Osp3JeF9XiTtMnrjjTUoQMq0DGyuKMCmIFGrkPKYylhWMiWZueotA0kUbis+aGR1k6FK4u6PHg5CbVINZl0zH0gJ81wwIMJ0MbZKETWy/aZdr1F4Am6wq5GBjulao61OUMjqxz4ssukxqi2YRsj/hCdlWVEg/nJaU8UpshFmtst9qjkqZSVGNrYQ8+xg==
    secret: AgBfqeTSl8o3EksXZ2E5cC3L9F5IkZzlwb64Sw3cUEZ3EvtrLyt5O3/OidMllcdOZI8EKstKKOxuBroJ3O44iloYFj3Ij1zAS2g8l8Px5SE4a5galhvJ2bRbYlg0HsA7EhsQPjqDOULWGKrIwyLw+9pQgDhXyG+vAdDGquq0L+DGdpK5l+OIWSs0V8cVmP3Znwp9bvSzJeepMHFHpCPSWz6ZYbUEi7nzcI9GA4JYnM1eEi9CyTBghU5RMAn1RPyDPA/PguCSOq4qSNHwr25VmRx5mPoP4ivLmsC2wBhVsT6WG4G27jUKlls8cneCnBvO2UAZhYrzLYj1ivfbaVQwbP8oKowMFNKrkTvUrnvb1AI75oVfBEKQusHk/RWxkaCBVaHk+OO+ro19o4l30x53Wbfu5giSLVJyuEt0pxEyqcFMKEPXVuwahbl6eMIW5fuXGFACZUck85A5kFYM2MlUCluIdAtXpVByaS2hOjBs3t20AztmGW7yDtLuw1csfTrf0twNyD7TvxFvjkKlQ94DVfGYNFAIbe63RNaFTxCK751HXH3XXBnCOKOUy1vF1jgFy757arSwP94RrysxuepEK7OIY7uhsBv38soQFryO3+WpDozf7EOWjYwG1adlauUGVaJhgbvqyKlPnkq7oL+B4Uu2U5o2pn1Erx8BhC8jugcIAKBuxXsloC7FhOg97NpVM2K+JVbKqjEBg8EnH9W8uaAyudJNOOtVhgAFOsqN9Q7rI2Hogqw1bsKh
  template:
    metadata:
      creationTimestamp: null
      name: oauth-github
      namespace: commento

