---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: etherpad-http
  namespace: etherpad
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: >-
        Host(`etherpad.agrrh.com`) || Host(`etherpad.5426b488.nip.io`)
      middlewares:
        - name: whitelist
          namespace: traefik
      services:
        - kind: Service
          name: etherpad
          namespace: etherpad
          port: 9001
