---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tg-keepi-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agrrh/keepi
    targetRevision: master
    path: kubernetes
    directory:
      recurse: true
  destination:
    namespace: tg-keepi-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
