---
# Source: baserow/templates/asgi-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: baserow-asgi
  namespace: baserow
  labels:
    helm.sh/chart: baserow-1.25.0
    app.kubernetes.io/name: baserow-asgi
    app.kubernetes.io/instance: baserow
    app.kubernetes.io/version: "1.19.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: baserow-asgi
    app.kubernetes.io/instance: baserow
