---
# Source: baserow/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow-frontend
  namespace: baserow
  labels:
    helm.sh/chart: baserow-1.25.0
    app.kubernetes.io/name: baserow-frontend
    app.kubernetes.io/instance: baserow
    app.kubernetes.io/version: "1.19.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: baserow-frontend
      app.kubernetes.io/instance: baserow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: baserow-frontend
        app.kubernetes.io/instance: baserow
    spec:
      serviceAccountName: baserow-frontend
      securityContext:
        fsGroup: 9999
        runAsGroup: 9999
        runAsUser: 9999
      containers:
        - name: baserow-frontend
          image: "baserow/web-frontend:1.19.1"
          imagePullPolicy: Always
          args:
            - nuxt
          env:
          envFrom:
            - configMapRef:
                name: baserow
            - configMapRef:
                name: baserow-frontend
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health
              port: 3000
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /_health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          securityContext:
            runAsGroup: 9999
            runAsNonRoot: true
            runAsUser: 9999
