---
# Source: baserow/templates/wsgi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-baserow-wsgi
  labels:
    helm.sh/chart: baserow-1.25.0
    app.kubernetes.io/name: baserow-wsgi
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.19.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: baserow-wsgi
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: baserow-wsgi
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-baserow-wsgi
      securityContext:
        fsGroup: 9999
        runAsGroup: 9999
        runAsUser: 9999
      containers:
        - name: baserow-wsgi
          image: "baserow/backend:1.19.1"
          imagePullPolicy: Always
          workingDir: /baserow
          args:
            - "gunicorn-wsgi"
            - "--timeout"
            - "60"
          env:
            # Baserow Backend Settings
            - name: BASEROW_JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: "release-name-baserow-backend"
                  key: jwt-signing-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "release-name-baserow-backend"
                  key: secret-key
            # Baserow Email Settings
            # Baserow File Upload Settings
            # Database Settings
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "release-name-postgresql"
                  key: "password"
            # Redis Settings
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "release-name-redis"
                  key: "redis-password"
          envFrom:
            - configMapRef:
                name: release-name-baserow
            - configMapRef:
                name: release-name-baserow-backend
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - --silent
                - http://localhost:8000/api/_health/
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - curl
                - --fail
                - --silent
                - http://localhost:8000/api/_health/
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
          securityContext:
            runAsGroup: 9999
            runAsNonRoot: true
            runAsUser: 9999
