---
# Source: baserow/templates/wsgi-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: baserow-wsgi
  namespace: baserow
  labels:
    helm.sh/chart: baserow-1.25.0
    app.kubernetes.io/name: baserow-wsgi
    app.kubernetes.io/instance: baserow
    app.kubernetes.io/version: "1.19.1"
    app.kubernetes.io/managed-by: Helm
