# ---
#
# kind: Application
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: metacontollers-ufoo
#   namespace: argocd
# spec:
#   project: initial
#
#   destination:
#     name: in-cluster
#     namespace: argocd
#
#   source:
#     repoURL: https://github.com/agrrh/infrastructure.git
#     targetRevision: master
#     path: kubernetes/ufoo/metacontrollers
#     # directory:
#     #   recurse: true
#
#   syncPolicy:
#     automated:
#       selfHeal: false
#       prune: false
