---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: payload-ufoo
  namespace: argocd
spec:
  project: initial

  destination:
    name: in-cluster
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/infrastructure.git
    targetRevision: master
    path: kubernetes/ufoo/payload
    # directory:
    #   recurse: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: false
