---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: payload-ufoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agrrh/infrastructure.git
    targetRevision: master
    path: kubernetes/ufoo/payload
    # directory:
    #   recurse: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
