apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config
  namespace: tg-dukhota-bot
spec:
  encryptedData:
    tg_token: AgCyfdxa8SA6MhxioJa7r5tRIKcLkx07ylxS/RcaqfAeqWE+cbk7TZOSh3vqCg/sTIjCIqla6d2SggtRo0uQjFQZvqUNNwUu4FW+kR1F/4AN5zPqw9ZXoPCmRpHbu89AmIrHUSYl1bE/1IjaGNI5Al5J/skc4GGxkN7TuWUuliiTCg/bkvvX5vPVavpkxVDJXkwh6EAGzKDu9Wj7dLFpZdth9hLLPUdth8LOHRXqeOnMTT7tHvdAXmSnYAj/r3cq0jnhjCvt5dvFgSDjJJMFvdFHPf+okbI7rAyhUXugj0QIHPphHZP60OYwae207HEtm0jEUr740HBp8YO/OiM2mMYPZopELDSHNK/cVkKsHrcybsoOj24mS1oHH7Dflezlv0fE4rPSbrqFl3E+HtEIGEW5/uf7Da7YZhDIzw2O654z4e34Tb5LVQgz/RG58HC1LrGmkilYWeZSJx8exzCwG1RmaoGH1ITJqRA5vXwbOjA7p9XMgYUmJU0STs2SuSICJvXrVPDAXpoONsbb9o/8fvmJwPD+KKSL3tKqD0M5rHpjSrHm+BcVCrbUCjlZ4awADxVwI45/Yo1OyHHg69QUiFAEsrpHrcolb1bNTucsJrLv2d2QsQLnYI9pCCf5lXj8KSgp+X4GOeykZHc91BwtAcHHK0aY3tta3UeI2kM9Gl050B3gP/zET5eoBMeKV8OVXim5LOpyCUT3LUyfcjpFb6pHFNp7ywzgqFt9mVg2N1S5JHAK+xuIEiopWgUIamnM
  template:
    metadata:
      creationTimestamp: null
      name: config
      namespace: tg-dukhota-bot

