---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nocodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: master  # 0.109.7
    path: charts/nocodb

    helm:
      releaseName: nocodb
      values: |
        extraEnvs:
          NC_PUBLIC_URL: https://nocodb.agrrh.com

        extraSecretEnvs:
          NC_AUTH_JWT_SECRET: oVi5mDVJSK8i1zrG
          NC_DB: "postgres://nocodb:nVwmMZGY5EcYrDtw@postgres:5432/nocodb?sslmode=disable"

        storage:
          size: 4Gi
          storageClassName: "microk8s-hostpath"

  destination:
    namespace: nocodb
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
