---

apiVersion: v1
kind: Service

metadata:
  name: nocodb
  namespace: nocodb
  labels:
    app: nocodb

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: nocodb
