---

kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1

metadata:
  name: crypto-exporter
  namespace: metrics
  labels:
    app: crypto-exporter
    release: kube-prometheus-stack

spec:
  endpoints:
    - honorLabels: true
      path: /
      port: http
      scheme: http
      interval: 30s
      scrapeTimeout: 15s
  jobLabel: prometheus
  namespaceSelector:
    matchNames:
      - metrics
  selector:
    matchLabels:
      app: crypto-exporter
