---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: openfaas
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://openfaas.github.io/faas-netes
    chart: openfaas
    targetRevision: 10.2.13

    helm:
      values: |
        # https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md#deploy-openfaas-community-edition
        operator:
          create: true
        functionNamespace: openfaas-fn
        generateBasicAuth: true

  destination:
    namespace: openfaas
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
