---
# Source: baserow/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: baserow-postgresql
  namespace: "baserow"
  labels:
    app.kubernetes.io/instance: baserow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.10.0
type: Opaque
data:
  postgres-password: "YlYyOENsQWRtOQ=="
  password: "YmFzZXJvdw=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
