apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: commento
spec:
  encryptedData:
    uri: AgBGPvDjrxH3mBOr0TfCFLyqgbOiW0ZS1U1ML77W+XlhxCP6/lMdfTO8RoDD1M2aOY+9pbWfjFnOIaXvHmixAHFiyEy10PnPbvLrA8IQTE6LB/Djg7uVRQZkm158o3MrWwEqzr0JoaonoqsP7rpSwJRWFs9yw5LDYYw4E/kh8p7krb6lDQNUl/dPZbr19m94KIn//XWhTQluGD2ccV8yRKbvfWcKN7FCy2xm0SeotJLc79rU+Pay5kz+ShNgBvah2IXRSNdNWM+X+JhJ3wiiDKDiYmKU8JRgNpBvJyMoayKzff70eFHBaciNZ1r0X3zCtm5HNLYXoha/mDYk4J8Mn2ZzwigqhYpvL2yg7FubWACG1f19XheiMjlJ402RWv3LjtQiwkdZ0IIX5DCcuB1ZIAGy14TA7F6Oih5w8UBOpJAEhSCfHy0nP60pie+bC+y+4ySsnTa9Wqu1Wub4B19QJCzNzzy0/VnBiF4JlmBybdFtkBzGPXqwyZkIqWz1MVUB068IJjMviUorTeTjytIWeEaFmiqLTeO8qTY897c5RD080cV/3Q7TWmpM986q6aPalX2QeUIyNTI9vLkqml36zJGSkwhOQmSusyHRDMd59zqy49Wucdj6C1w+uZW+LsJn5IrphB/gZAPVPjshSJBdg8hMLI84CEb40arvl5OL9XBZ4TwI1mzaj4DZMjWyrkRJksBvqfZfFgsDkiFEKe2MRRqP9Et3QwmgKtZsqCfD90u9YaRVm4lCX6NYSpw5h4YtwnV/U0jT2dCtREla+9GP/zxIyh+pL6DeIGifZ4QkSNNAZ/s6zAI=
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: commento

