# NOTE Loki: like Prometheus, but for logs.
#   https://grafana.github.io/loki/charts/

---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "4.7.0"
    helm:
      # https://github.com/grafana/loki/blob/v2.5.0/production/helm/loki/values.yaml
      values: |
        ---
        ingress:
          enabled: false

        loki:
          auth_enabled: false

        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 10Gi
          storageClassName: microk8s-hostpath

  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
