---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: etherpad-extras
  namespace: argocd
spec:
  project: payload

  destination:
    name: k3s.spb.agrrh.com
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: master
    path: kubernetes/dogseen/payload/apps/etherpad/extras
    directory:
      recurse: false

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
