---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: payload-etherpad
  namespace: argocd
spec:
  project: payload
  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: master
    path: kubernetes/ufoo/payload/apps/etherpad
    directory:
      recurse: true
  destination:
    namespace: payload
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
