# ---
#
# kind: Application
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: meta-hello
#   namespace: argocd
# spec:
#   project: payload
#   source:
#     repoURL: https://github.com/agrrh/infrastructure.git
#     targetRevision: master
#     path: kubernetes/ufoo/payload/metacontrollers/hello
#     directory:
#       recurse: true
#   destination:
#     namespace: argocd
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       selfHeal: false
#       prune: false
