---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-agent-custom
  namespace: vector
data:
  vector.yaml: |-
    # NOTE https://vector.dev/docs/reference/configuration/

    sources:
      vector_logs:
        type: internal_logs

      vector_metrics:
        type: internal_metrics

      syslog:
        type: syslog
        mode: tcp
        address: 0.0.0.0:514
        max_length = 102_400

    transforms:
      parse_syslog:
        type: remap
        inputs:
          - my-source-or-transform-id
        source: . |= parse_syslog!(.message)

    # NOTE Outputs

    sinks:
      # NOTE Uncomment if you need to send stream to Vector's output
      # console:
      #   type: console
      #   inputs:
      #     - vector_logs
      #   encoding:
      #     codec: json

      syslog_to_loki:
        type: loki
        inputs:
          - parse_syslog
        endpoint: http://loki.loki.svc:3100
        # labels:
        #   node: "{{ "{{ kubernetes.pod_node_name }}" }}"
        encoding:
          codec: json

      prometheus_sink:
        type: prometheus_exporter
        inputs:
          - vector_metrics
        address: 0.0.0.0:9090
