---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-agent-custom
  namespace: vector
data:
  vector.yaml: |-
    # NOTE https://vector.dev/docs/reference/configuration/

    sources:
      vector_logs:
        type: internal_logs

      vector_metrics:
        type: internal_metrics

      kubernetes_logs:
        type: kubernetes_logs

    transforms:
      kubernetes_json:
        type: remap
        inputs:
          - kubernetes_logs
        source: |-
          .vector_messages = []

          # {\"data\":<...>}
          parsed, err = parse_json(.message)
          if err != null {
            .vector_messages = push(.vector_messages, "parse_json_failed")
          } else {
            .json = parsed
            del(.message)
          }

    # NOTE Outputs

    sinks:
      # NOTE Uncomment if you need to send stream to Vector's output
      # console:
      #   type: console
      #   inputs:
      #     - vector_logs
      #   encoding:
      #     codec: json

      kubernetes_to_loki:
        type: loki
        inputs:
          - kubernetes_json
        endpoint: http://loki.loki.svc:3100
        labels:
          node: "{{ "{{ kubernetes.pod_node_name }}" }}"
          namespace: "{{ "{{ kubernetes.pod_namespace }}" }}"
          container: "{{ "{{ kubernetes.container_name }}" }}"
          app: "{{ "{{ kubernetes.pod_labels.app }}" }}"
        encoding:
          codec: json

      prometheus_sink:
        type: prometheus_exporter
        inputs:
          - vector_metrics
        address: 0.0.0.0:9090
