---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tg-personal-assistant-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agrrh/tg-personal-assistant
    targetRevision: master
    path: kubernetes/prod
    directory:
      recurse: true
  destination:
    namespace: tg-personal-assistant-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
