---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: metrics
spec:
  encryptedData:
    admin-password: AgCEZ/NF1hpb4bs7+EQaJ8WBGN92drmBAWy/OAFh92Nt9ah5yUayuMNMxk4AKTCBozxkCKFcTyR5OjuJg9gw7TXueQYfpYNKpcxCzsnf2TL3XzEAwS9+JN6L1wp+vj6LjIMpFJKXs9r6sAemuIUXUSVxyMyPoWs+C4XpykRFUQSXtLNcZwYtXKCy26vW1/pUzAK/S1V6yDYrPicY/Lx01lbASj2iJZZ3DQnUx4AoAy34+DLGWB7gMCO1kTz1z6dSx6WH4lbBt2TB6MW8K+iUCZ4tkAtI1SM74MjgsrP3/aPSTkkZbqEn7MF3Us1SWtlgkHg34mmphNyevIkk2REUgj1w/7QWtHQ3qgshED/6/PXEoVlfbxUo25NKBT9TeqP/vi+9fSGpOMJLfC+iAxrxqkLAJNpZn6eMSEaebxqiPCIspUCIbyLmWXFUfHk3MYGYXdNCIf5VVD4u2TkiXZIcPtrv23WieC6l8kwrhZnA2GQzTa52G1247hciVAjk6WygMEBdwPB4iBhpFS58/FwfsVQp4YCb2xL3IordsGqqlBFAXmk2z8Le2AEYbuvhYT4j6rc3I2sIncnZPwRglAcOjUmKDd/Hd/fJsQlMzLPWgpqPm/p/mXLKB26b1NITw31Q3c2sDGb8F2XDUt18R9Pwt3xF5U7FmsU1lvA0OhvQhTmBVaUAzerGol1YguGIqAPVP57NbX2WjmtqDps0
    admin-user: AgCUbBBR4bsekTGDiq9odlvDU1nZC7phtIvzftyu7o561HppZz3cB8V0kH+PVq5UB2B4BQJIzjTjsxCCshJ9EN9ce/4paJMncuDr02HKWl8Ed+YV73FryjiurVQ6FaStL9ip/L0kEdlYshGbDWWfdLbHA8cZgVJWiAM1WUKaPjw4q06omnhjhXCHrfaL/bi1M4VOqkht+puNdc8RQk7UpZrOzpjTUXCW1VQ/7NHTHqHz1QMOI4m3Ual9Lvak15rN5Io9G5rU2cTLbzZMdiWjFbZBTjq3yBp/t2VnwqU/YiEe1ScFNOC0uS/JRFsOZn1z2cfiJ8NiYZfd0hJ+MZiNJ/VP/2lv6t9py/jnSP/d42ex7JdJ5K3ERbqKjrtyc4ukqhM3xrzanGSwbNfqEPQEMhVwRpbG1oyf4uQblq1Fi9dY4PCVacClegRg3e1cmJSu83DLoCUbNKzn2nOZ9BQk7HcCHCg1ttjL1dNbjJJxKPsXjV1vvMilceNReOnge//Zy3wnknkBdNgjCSrMe8D0ly8EjTJupp0zOpF3nrpkFDtU/XzNE89HgpEhpReVN11Me47MrJXsbyCUE39tG7KL6VGKy4ymI9IYLG0w+CHbIfOW/jJRRqDao9gB0m8Fj0ywpg8cF52leLXwaF+Tn2WAeIwxXoODV5rbRHRkfFX5FbdI0R5evrp3T/QmQSy4EQfOvw0NjYK6Ww==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: metrics
