---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: tech

  destination:
    name: brave-booth
    namespace: metrics

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.0.0

    helm:
      values: |
        # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-45.0.0/charts/kube-prometheus-stack/values.yaml

        alertmanager:
          enabled: true

        alertmanagerSpec:
          tolerations:
            - effect: NoSchedule
              key: agrrh.com/node-role
              operator: Equal
              value: master

        defaultRules:
          create: false

          runbookUrl: https://runbooks.prometheus-operator.dev/runbooks

        grafana:
          enabled: false

          additionalDataSources: []
          admin:
            existingSecret: grafana-admin
            userKey: admin-user
            passwordKey: admin-password

          defaultDashboardsEnabled: true
          defaultDashboardsTimezone: browser

        # NOTE: Disable scrapes as those are too heavy for my toy setup
        kubeApiServer:
          enabled: false
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: false
        coreDns:
          enabled: false
        kubeDns:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false

        prometheusOperator:
          admissionWebhooks:
            tolerations:
              - effect: NoSchedule
                key: agrrh.com/node-role
                operator: Equal
                value: master

          tolerations:
            - effect: NoSchedule
              key: agrrh.com/node-role
              operator: Equal
              value: master

        prometheus:
          enabled: true

          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi
                  storageClassName: local-path

        prometheusSpec:
          tolerations:
            - effect: NoSchedule
              key: agrrh.com/node-role
              operator: Equal
              value: master

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.persistentVolumeClaimRetentionPolicy[]
