---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: operator-lifecycle-manager
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://github.com/clayrisser/charts/tree/main/stable/olm
    targetRevision: main

    helm:
      values: |
        # changeme

  destination:
    namespace: operator-lifecycle-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
