---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: payload-etherpad
  namespace: argocd
spec:
  project: payload

  destination:
    name: in-cluster
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: master
    path: kubernetes/dogseen/payload/apps/etherpad
    directory:
      recurse: false

  syncPolicy:
    automated:
      selfHeal: false
      prune: false
