---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: hajimari
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://hajimari.io
    chart: hajimari
    targetRevision: "2.0.2"
    helm:
      releaseName: hajimari
      values: |
        # https://github.com/toboshii/hajimari/tree/main/charts/hajimari
        #
        # Also this chart inherits from the bjw-s library chart.
        # You can check the default values/options here:
        # https://github.com/bjw-s/helm-charts/tree/main/charts/library/common

        image:
          repository: agrrh/hajimari
          pullPolicy: IfNotPresent
          tag: v0.3.2

        env:
          TZ: Europe/Moscow

        serviceAccount:
          create: false

        persistence:
          data:
            enabled: true
            accessMode: ReadWriteOnce
            size: 1Gi

        hajimari:
          instanceName: null
          defaultEnable: false
          namespaceSelector:
            any: true

            # matchNames:
            #   - default
            #   - downloads
            #   - media

          name: Kirill
          title: Hajimari

          lightTheme: gazette
          darkTheme: horizon

          customThemes:
            - name: one-dark
              backgroundColor: '#21252b'
              primaryColor: '#abb2bf'
              accentColor: '#585f6c'
            # - name: danger
            #   backgroundColor: '#0c0e0c'
            #   primaryColor: '#eaebea'
            #   accentColor: '#d8323c'

          showGreeting: true
          showAppGroups: true
          showAppUrls: false
          showAppInfo: true
          showAppStatus: false
          showBookmarkGroups: true
          showGlobalBookmarks: false
          defaultAppIcon: mdi:application
          alwaysTargetBlank: false

          defaultSearchProvider: Google
          searchProviders:
            - name: Google
              token: g
              icon: simple-icons:google
              searchUrl: https://www.google.com/search?q={query}
              url: https://www.google.com
            # - name: DuckDuckGo
            #   token: d
            #   icon: simple-icons:duckduckgo
            #   searchUrl: https://duckduckgo.com/?q={query}
            #   url: https://duckduckgo.com
            # - name: IMDB
            #   token: i
            #   icon: simple-icons:imdb
            #   searchUrl: https://www.imdb.com/find?q={query}
            #   url: https://www.imdb.com
            # - name: Reddit
            #   token: r
            #   icon: simple-icons:reddit
            #   searchUrl: https://www.reddit.com/search?q={query}
            #   url: https://www.reddit.com
            - name: YouTube
              token: 'y'
              icon: simple-icons:youtube
              searchUrl: https://www.youtube.com/results?search_query={query}
              url: https://www.youtube.com

          customApps: []
            # - group: Media
            #   apps:
            #     - name: Test
            #       url: 'https://example.com'
            #       icon: 'mdi:test-tube'
            #       info: This is a test app

          globalBookmarks:
            - group: Communicate
              bookmarks:
                - name: Discord
                  url: 'https://discord.com'
                - name: Gmail
                  url: 'http://gmail.com'
                - name: Slack
                  url: 'https://slack.com/signin'
            # - group: Cloud
            #   bookmarks:
            #     - name: Box
            #       url: 'https://box.com'
            #     - name: Dropbox
            #       url: 'https://dropbox.com'
            #     - name: Drive
            #       url: 'https://drive.google.com'
            # - group: Design
            #   bookmarks:
            #     - name: Awwwards
            #       url: 'https://awwwards.com'
            #     - name: Dribbble
            #       url: 'https://dribbble.com'
            #     - name: Muz.li
            #       url: 'https://medium.muz.li/'
            - group: Dev
              bookmarks:
                - name: Codepen
                  url: 'https://codepen.io/'
                - name: Devdocs
                  url: 'https://devdocs.io'
                - name: Devhints
                  url: 'https://devhints.io'
            # - group: Lifestyle
            #   bookmarks:
            #     - name: Design Milk
            #       url: 'https://design-milk.com/category/interior-design/'
            #     - name: Dwell
            #       url: 'https://www.dwell.com/'
            #     - name: Freshome
            #       url: 'https://www.mymove.com/freshome/'
            # - group: Media
            #   bookmarks:
            #     - name: Spotify
            #       url: 'http://browse.spotify.com'
            #     - name: Trakt
            #       url: 'http://trakt.tv'
            #     - name: YouTube
            #       url: 'https://youtube.com/feed/subscriptions'
            - group: Reading
              bookmarks:
                - name: Instapaper
                  url: 'https://www.instapaper.com/u'
                - name: Medium
                  url: 'http://medium.com'
                - name: Reddit
                  url: 'http://reddit.com'
            - group: Tech
              bookmarks:
                - name: TheNextWeb
                  url: 'https://thenextweb.com/'
                - name: The Verge
                  url: 'https://theverge.com/'
                - name: MIT Technology Review
                  url: 'https://www.technologyreview.com/'

  destination:
    namespace: hajimari
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
