---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: hajimari
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://hajimari.io
    chart: hajimari
    targetRevision: "2.0.2"
    helm:
      releaseName: hajimari
      values: |
        # https://github.com/toboshii/hajimari/tree/main/charts/hajimari
        #
        # Also this chart inherits from the bjw-s library chart.
        # You can check the default values/options here:
        # https://github.com/bjw-s/helm-charts/tree/main/charts/library/common

        image:
          repository: agrrh/hajimari
          pullPolicy: IfNotPresent
          tag: v0.3.2

        env:
          TZ: Europe/Moscow

        serviceAccount:
          create: false

        persistence:
          data:
            enabled: true
            accessMode: ReadWriteOnce
            size: 1Gi

        hajimari:
          instanceName: null
          defaultEnable: false
          namespaceSelector:
            any: true

            # matchNames:
            #   - default
            #   - downloads
            #   - media

          name: Kirill
          title: Hajimari

          lightTheme: one-dark
          darkTheme: one-dark

          customThemes:
            - name: one-dark
              backgroundColor: '#21252b'
              primaryColor: '#abb2bf'
              accentColor: '#585f6c'

          showGreeting: true
          showAppGroups: true
          showAppUrls: false
          showAppInfo: true
          showAppStatus: false
          showBookmarkGroups: true
          showGlobalBookmarks: false
          defaultAppIcon: mdi:application
          alwaysTargetBlank: false

          defaultSearchProvider: Google
          searchProviders:
            - name: Google
              token: g
              icon: simple-icons:google
              searchUrl: https://www.google.com/search?q={query}
              url: https://www.google.com
            - name: Kinopoisk
              token: k
              icon: simple-icons:kinopoisk
              searchUrl: https://www.kinopoisk.ru/index.php?kp_query={query}
              url: https://www.kinopoisk.ru
            - name: YouTube
              token: 'y'
              icon: simple-icons:youtube
              searchUrl: https://www.youtube.com/results?search_query={query}
              url: https://www.youtube.com
            - name: Yandex
              token: 'z'
              icon: mdi:search-web
              searchUrl: https://yandex.ru/search/?text={query}
              url: https://yandex.ru

          customApps: []
            # - group: Media
            #   apps:
            #     - name: Test
            #       url: 'https://example.com'
            #       icon: 'mdi:test-tube'
            #       info: This is a test app

          globalBookmarks:

            - group: Social
              bookmarks:
                - name: Pikabu
                  url: 'https://pikabu.ru'

            - group: Tech
              bookmarks:
                - name: Habr
                  url: 'http://habr.com'
                - name: Vas3k
                  url: 'http://vas3k.ru/all/'

            - group: News
              bookmarks:
                - name: Oper.ru
                  url: 'https://oper.ru'
                - name: Fontanka
                  url: 'http://fontanka.ru'

  destination:
    namespace: hajimari
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
