apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth
  namespace: hajimari
spec:
  encryptedData:
    password: AgBjtDJugpclS5K1HdV00D/I9zm90KHpbZjfhRm4nFApko9SxGJG8iuX49ovHDEd/O69XwPw/xtHFVciQW4jFsOSizrU6/jmBLb5qoZabDFeCjB/Efl34FvRolw2/CR5QHHGXJ3CPZB7afvr/7ZcAbI0g3gfe1bOhZUwLvwN7ZaI6LrLcwyLpPwwA8zqj+xehiIBE0YOKCHAJ2AQmC/qYjmDenUj3A740svq9j4/+pN3oYUM2cXwAph64xPatfzddfQjj94yhGWm+EBazso/YH6Fo9gdR8UGxTKLSsTaWKaJVvzCZlWnSvxeCt6+PZ8p2pzieFE/KivhZ9EWwN3+DaVLHbaS3JlzRjhtUrDZnDcCX9lWQNl9+JI6PRWy4JswbDDF/gldZL9w+2BNuxX+Lp7uLjCyLLWdEqTAP2CSvo8KD8bx8asWBJw+e6AYR/ALayC24ZN7Ysaqj8hoquQupwHzIXfd6EwKoFNSF+Y6o0ToKv75XJNJCFXPr12RNJqlC+tfdlou8YkZ78CbIFucEO9L/ajAX3uk7JBIslLksh0jxrcQTEvI0oPrPiWo9SdAMrxXp1LZQmm1nrFqolXKE70XGrNEoLAAAI6TlctF04utYCTEgvLNFXZmR7PlasVZXLkp+g3/Chuk+8HaMpPsqVqz2K9yDCkA42/VriESD/MScGdLX1YU7HhErSuNOgCEM1euKLGgtpthYBLe
    username: AgB9Bg469Ne48NYFLzb4WCW5oxz7braSJnNZaAOB0sOH6bHm3y9Wg/xy5S4s6Y/AFoI28JMqStEPdLNCVxadw2m+3lj7kPgP4WTpdV1myu0rAdb0LT+WlqJgwE7sLdjFw9RpC6+Hwnma43xqhnc86TNs3Gw/JGsMfeFn2vKJ1mCKZ9XCMj5OweLcZJy4V96P7rnDpupE9pkD6mxUUwCMHny/eWtf61KDp9mahUuqfb19Tp8PfFvBlBk1kTkz+Gvg0sfU+z+/RKq77DuQCBNnSNNRK80R2LcrXa61QiQh7FAgv1R+BndSNqgnrrpBgTArZsVTDrMgU+ueCEB2tIJSN5QXQml3fdvwAmlTjCPG6YqyFw8KoF++NQ8F4Yr2IyL5AQBRIRPOV9+7c17kytSbQIHH+oaay6d+9EI0grlDQJWGBntOPe2YtaOFfpQRnD68nL9G3dQ+3psMZIhQUoLiwwFQizSaUJt3wc/GrIcDOOEoznIJjXS/2H1IgeCXw3Lc0hBrIXWOa1Bd6WZMYtsXgwEVHElbKAEPw50bL9YOSLwllHT8IRErBcDDzjs+gM56AuBxDcHOEODULGfgPld7axsXtj+LPmAH7Wm1FDaZR2JE5TdccfxBXRyqp3HmFvijFoiXO5laaPNWfknV6EI6E8be5v4RxAMqx31IkvkFsvewm4YYmBodKLHQRd/YEPslRW/Sba87Yg==
  template:
    metadata:
      creationTimestamp: null
      name: auth
      namespace: hajimari
    type: kubernetes.io/basic-auth

