---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: operator-lifecycle-manager
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://github.com/operator-framework/operator-lifecycle-manager.git
    targetRevision: v0.25.0
    path: deploy/chart

    helm:
      values: |
        # changeme

  destination:
    namespace: operator-lifecycle-manager
    name: k3s.spb.agrrh.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
