---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: keel
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://charts.keel.sh
    chart: keel
    targetRevision: 1.0.2

    helm:
      values: |
        namespace: kube-system

        webhook:
          enabled: true
          endpoint: "https://fn.agrrh.com/function/keel-webhook"

  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
