---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-provision
  namespace: db-personal
spec:
  encryptedData:
    password: AgDL5heRmcxK36NdtUeKTTq628x3W03kmGiNlWWahGdeUHPa9+f0RlfXGDs44aDfNRwMSJwJUuID8O+Hg1rlwUBx4iaUUyvhyJcVwPRXDmvvlasmU34AQa8P8jErfU7XCxGky2u2DwxDS0P+zRVC+AMnZHsIZtSpq7cEgCvHdTNsE+PkZMsPRW1GaKxEyPDRlB4UxeDDRDJI0VGH5noLH3JqdHnmI6S0RVLqjHOMjpk5v1ENnb4uXecHG94CJM/shw3B+J/3cRgiDKB5LxfiblBhqgomOZC8YnbTUMJ6jgz77Ehw+dRH7X2MGlheM4h1YvKhz53Tfb5fYqxM0sqDlq0eXpERcl08boBkqxYgLPhOTJXhcCWVHJqRwQUVWI30a4gsrtw+Cf0GPVOCDqEDXdAAOrcPR35w2ot3U86M3a6NGDUDtkioYfdT6Gaw818rCZvciP1VCaN5jMbHl5beevhSPBx9kVYzri30+Utx57MMtz1FUv0cVMyMYbWOhjvIX/Cb2nqhfMZ6MnlliG9t4TVyIySc+ezFzDNURVip0O4coSDi/5mk/NRS0V7VnyBUNvrp66ZPl70xVXMsgiB7Cpw8Y8ruBRZ7RzcDeQX0xS0JEdS4Iv0FzVTy3pLk+dzrWlgNnBioi5d3dDOittFBcBVfHm7fSyJLlDF543Ae/tX9C7hsIb9sYpncCTiBR7pvET3OnSkq0nCP9vh97k4u0I349hQ0dpsszWM=
    user: AgCs7L9YP+DAtskVp0FL6WoNRh2aclVjbWs1h7HakX9FRb3qUMzPNUOoS3IiG+w3Hhe73iTFQdlNs0rL7Fx6Mdj9Et5p40VkQ6nqy30/OhtrpYscQqg2E7oKQk041ObutQPGVd/scRSM5VZgcKWczFKcJylYxP2JNRroUP+4pFlzDX9+bPCYjLLQClhGsszGMe7aoVB9VQ6Sg8dR2AB7/YEeWFqDAhx534PEL84/ksy4kOJ+f6vDqJzb8PMqplP+LIMu+Vkvgg6o6giut+xgJJdh2vaxRcpL/0jMsktiiZ0zT6gGqUB988T8E1ZfBJSQ0NFCiZDfmbhWntrB6ifpY/aN3g8LGtz5Zwl18Mq5hBS/O8gznSc66TZ20CA4cvQXobv8nsX8vyu7fFtPLhj+tAkq+dycymx80Ix6/xgBna2M+cpo9VtiO4RPNhMv0kDkGJif7/L6WKhxprMm1XMX/64yPSxg99h+pUrbimDj9zPdl4KBqWk/JCVFtMtCQVFxig7DGli0vFtbESd96IDKEEggoT0NoDEk/B9sEmRwa/IFPu/AN/5CYrZp6F2H7FlkjXhnGbPZo58skep0Zmq/VnqiGK+V69gMyA8MOKatCApzrjmslydAWvl5HHqiKWp2UVAPqLgATBWW6u6bkBHWus8XuwvZ6UvLOlszolDfPIHlzSSD3bl/9N0MjSQGhLtfUNmz5tJEtcnDp40=
  template:
    metadata:
      name: postgres-provision
      namespace: db-personal
