---
# Source: baserow/templates/backend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: baserow-backend
  namespace: baserow
data:
  # Baserow Backend Settings
  BASEROW_ACCESS_TOKEN_LIFETIME_MINUTES: "10"
  BASEROW_AIRTABLE_IMPORT_SOFT_TIME_LIMIT: "1800"
  BASEROW_BACKEND_DATABASE_LOG_LEVEL: "ERROR"
  BASEROW_BACKEND_DEBUG: "off"
  BASEROW_BACKEND_LOG_LEVEL: "INFO"
  BASEROW_FILE_UPLOAD_SIZE_LIMIT_MB: "1048576"
  BASEROW_REFRESH_TOKEN_LIFETIME_HOURS: "168"
  BASEROW_ROW_PAGE_SIZE_LIMIT: "200"
  BASEROW_SNAPSHOT_EXPIRATION_TIME_DAYS: "360"
  BASEROW_SYNC_TEMPLATES_TIME_LIMIT: "1800"
  BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION: "true"
  BATCH_ROWS_SIZE_LIMIT: "200"
  MIGRATE_ON_STARTUP: "true"
  POSTGRES_STARTUP_CHECK_ATTEMPTS: "5"
  # Baserow Backend Misc Configuration
  BASEROW_INITIAL_CREATE_SYNC_TABLE_DATA_LIMIT: "5000"
  BASEROW_JOB_CLEANUP_INTERVAL_MINUTES: "5"
  BASEROW_JOB_EXPIRATION_TIME_LIMIT: "43200"
  BASEROW_JOB_SOFT_TIME_LIMIT: "1800"
  BASEROW_MAX_FILE_IMPORT_ERROR_COUNT: "30"
  BASEROW_MAX_ROW_REPORT_ERROR_COUNT: "30"
  MINUTES_UNTIL_ACTION_CLEANED_UP: "120"
  # Baserow Celery Settings
  BASEROW_AMOUNT_OF_WORKERS: ""
  BASEROW_CELERY_BEAT_DEBUG_LEVEL: "INFO"
  BASEROW_CELERY_BEAT_STARTUP_DELAY: "15"
  BASEROW_RUN_MINIMAL: ""
  # Baserow Email Settings
  # Baserow File Upload Settings
  AWS_STORAGE_BUCKET_NAME: ""
  MEDIA_ROOT: "/baserow/media"
  MEDIA_URL: "$PUBLIC_BACKEND_URL/media/"
  # Baserow Webhook Settings
  BASEROW_WEBHOOKS_MAX_CALL_LOG_ENTRIES: "10"
  BASEROW_WEBHOOKS_MAX_CONSECUTIVE_TRIGGER_FAILURES: "8"
  BASEROW_WEBHOOKS_MAX_PER_TABLE: "20"
  BASEROW_WEBHOOKS_MAX_RETRIES_PER_CALL: "8"
  BASEROW_WEBHOOKS_REQUEST_TIMEOUT_SECONDS: "5"
  BASEROW_WEBHOOKS_URL_CHECK_TIMEOUT_SECS: "10"
  # Database Settings
  DATABASE_HOST: "baserow-postgresql"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "baserow"
  DATABASE_USER: "baserow"
  # Redis Settings
  REDIS_HOST: "baserow-redis-master"
  REDIS_PORT: "6379"
