---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: drone-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.drone.io
    chart: drone-runner
    targetRevision: 0.1.10

    helm:
      values: |
        # https://artifacthub.io/packages/helm/drone/drone-runner-kube

  destination:
    namespace: drone
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
