---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: drone-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.drone.io
    chart: drone
    targetRevision: 0.6.3

    helm:
      values: |
        # https://artifacthub.io/packages/helm/drone/drone

        env:
          TZ: Europe/Moscow
          DRONE_SERVER_PROTO: https
          DRONE_SERVER_HOST: drone.agrrh.com
          # https://community.harness.io/t/drone-server-changing-ports-protocol/11400
          DRONE_SERVER_PORT: ":80"

        extraSecretNamesForEnvFrom:
          - config

  destination:
    namespace: drone
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
