---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: traefik
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 10.24.3

    helm:
      values: |
        # https://github.com/traefik/traefik-helm-chart
        deployment:
          enabled: true
          replicas: 2
        env:
          - name: TZ
            value: Europe/Moscow
        globalArguments:
          - --global.checknewversion
          - --global.sendanonymoususage
        additionalArguments:
          - --accesslog=true
          - --accesslog.format=json

          - --providers.kubernetescrd.allowCrossNamespace=true

          - --entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.40.0/24,10.0.55.0/24,84.38.180.136/32
          - --entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.40.0/24,10.0.55.0/24,84.38.180.136/32

          - --entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.40.0/24,10.0.55.0/24,84.38.180.136/32
          - --entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.40.0/24,10.0.55.0/24,84.38.180.136/32

        image:
          name: traefik
          pullPolicy: IfNotPresent
          tag: ""
        ingressRoute:
          dashboard:
            enabled: true
        logs:
          access:
            enabled: false
          general:
            level: WARNING
        metrics:
          prometheus:
            entryPoint: metrics
        persistence:
          enabled: false
        pilot:
          enabled: false

        service:
          enabled: true
          type: NodePort
          spec:
            externalTrafficPolicy: Local
            internalTrafficPolicy: Local

        ports:
          web:
            expose: true
            exposedPort: 80
            port: 8000
            protocol: TCP
            nodePort: 32080
          websecure:
            expose: true
            exposedPort: 443
            port: 8443
            protocol: TCP
            nodePort: 32443
            tls:
              certResolver: ""
              domains: []
              enabled: false
              options: ""
          metrics:
            expose: false
            exposedPort: 9100
            port: 9100
            protocol: TCP
          traefik:
            expose: false
            exposedPort: 9000
            port: 9000
            protocol: TCP

        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
            allowEmptyServices: false
            allowExternalNameServices: true
          kubernetesIngress:
            enabled: true
            allowEmptyServices: false
            allowExternalNameServices: true
            publishedService:
              enabled: false

  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
