---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: redis
  namespace: n8n

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
