---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: nocodb
  namespace: nocodb
  labels:
    app: nocodb

spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: nocodb
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      containers:
        - name: main

          image: nocodb/nocodb:0.255.2

          env:
            - name: NC_DB
              value: sqlite:///usr/app/data/data.db

            - name: NC_PUBLIC_URL
              value: https://nocodb.agrrh.com

            - name: NC_DISABLE_TELE
              value: "true"

            - name: NC_AUTOMATION_LOG_LEVEL
              value: "ALL"

            # Caching

            - name: NC_REDIS_URL
              value: redis://redis:6379/0

            # Enables litestream, https://litestream.io

            - name: LITESTREAM_SYNC_INTERVAL
              value: "60s"

            - name: LITESTREAM_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-litestream
                  key: LITESTREAM_S3_ACCESS_KEY_ID

            - name: LITESTREAM_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-litestream
                  key: LITESTREAM_S3_BUCKET

            - name: LITESTREAM_S3_PATH
              valueFrom:
                secretKeyRef:
                  name: s3-litestream
                  key: LITESTREAM_S3_PATH

            - name: LITESTREAM_S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-litestream
                  key: LITESTREAM_S3_ENDPOINT

            - name: LITESTREAM_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-litestream
                  key: LITESTREAM_S3_REGION

            - name: LITESTREAM_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-litestream
                  key: LITESTREAM_S3_SECRET_ACCESS_KEY

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          ports:
            - name: http
              containerPort: 8080

          volumeMounts:
            - mountPath: /usr/app/data/
              name: data-volume

      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: nocodb-sqlite
