---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nocodb-sqlite
  namespace: nocodb
  labels:
    app: nocodb

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
