---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: app-day-to-remember
  namespace: argocd

spec:
  project: personal

  destination:
    name: brave-booth
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/day-to-remember
    targetRevision: HEAD
    path: deployment/production
    directory:
      recurse: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: false
