---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: concourse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: concourse
    targetRevision: 2.0.2

    helm:
      values: |
        # https://artifacthub.io/packages/helm/bitnami/concourse

        global:
          storageClass: microk8s-hostpath

        secrets:
          localUsers: >-
            agrrh:fiftyonepw

        service:
          web:
            type: ClusterIp

        web:
          baseUrl: "/"
          externalUrl: "https://concourse.agrrh.com"
          auth:
            duration: 168h

        worker:
          mode: deployment
          replicaCount: 1
          baggageclaim:
            # detect, naive, btrfs, overlay
            driver: detect

          # NOTE: Set globally
          # persistence:
          #   storageClass: microk8s-hostpath


  destination:
    namespace: concourse
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
