---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: payload-dogseen
  namespace: argocd

spec:
  project: initial

  destination:
    namespace: argocd
    name: in-cluster

  source:
    repoURL: https://github.com/agrrh/infrastructure.git
    targetRevision: master
    path: kubernetes/dogseen/payload
    # directory:
    #   recurse: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
