---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: tech-dogseen
  namespace: argocd

spec:
  project: initial

  destination:
    name: k3s.spb.agrrh.com
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/infrastructure.git
    targetRevision: master
    path: kubernetes/dogseen/tech
    # directory:
    #   recurse: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
