---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: tech-dogseen
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/agrrh/infrastructure.git
    targetRevision: master
    path: kubernetes/dogseen/tech
    directory:
      recurse: true
  destination:
    namespace: argocd
    name: k3s.spb.agrrh.com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
