---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: archivebox
  name: archivebox
  namespace: archivebox
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
