---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: archivebox
  namespace: archivebox
  labels:
    app: archivebox

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
