---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard
  namespace: archivebox
spec:
  encryptedData:
    wg0.conf: AgBjuh7OgdeujSfRtlmYtX5OTK4ayL9LhDgh+AmPaqUZ1ogTjy13b+gkc+dyd0FU4cOySqafRzqI9IH/XOscXdAYrYWsFmnLzJLJxDJrV2mCvENCuXB2cumrcpIPz7p+/kuMPfbTCrYibTPWJIQgZ6rDRpLRhXDxfLuF1V9FUJ66e3QW8GYfr44r/YARsRz4waVnwvWVBSTSpGPcx9aVS/s70mU60EFQizu3klZ1EaJkbp0l/XWdxmmxpyAl68SFf3k7OF2vloaTO9ni+M3pA4Is1f4D/Lf0H72lXHFD7dEupZmvUw9nApIT8JTsOtK52xlo9HC5EXDDH96ko/croEp4WLRLykrvMImeEFjn3vefu8Atw88vGfnjspOZEXcKyeY/1RBtUkne9FTucUthGFsRZUwG+772GjO9YDWiOL1ZeaXxp9boKHUYEtmkA8k+ulaLkYMvFpZoY6CklnN5kqu6YiHNmROLuKS7fZW6t6acTCzmNHI31Gb1LKuRNW369oszPFCclr+tp8eZYJ35j7nZztEZ4+1yQMa/lHSkj6QYMJa8luV/jXsI1CaAX5skoTjUvGsAAWbXXSGhRTh3TssK1odq4AiKz1lZ2pJGXZsOUypCwbztYPpPanb37FLGfsm2mL2UgjtuqPG0KckdqGjd9Fa6m9ALSgWDtohQVZxFp7UVdu/eJYKd49w5W7I0J60Cz6BHjhDuw4P2+CRo/9P1ywKzmlzHvXMYcPC0akjCffbzCCyn8aoqaFIPo5V54op1xwpDt0IRUtnZno42MRgMG/aRfCOb9k793tNrfr0adTt0cBdHDih4jb9E75YLjtr9a+5c/T1KwKaWeC2NP2Vo3SobsV1N5QYh9eYBu5vGyyMrX2Nplb5upXKr4lZAK+mbrCyGu576Olj3iAntKVIs/OUx2RzGVgPaJJH4xmhrBvgyoMtNYs+ZEGVEfboaqrYjhzPzpn6B6xJGTj7CDYmYQu1VJUHszgd0qwDMdCA6Bpr0nQNrPGYwez0OLH615Wl7Xpw9tZ6Jj54D+HZePmVIcUt12lvyusmAZ1QRzvYuwHCtCdgl169m1x16vCibxRvOYVhESBzvWiGgokawF2i+vkaXGB8aGULiOuN3bPw1CXDzOZI=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard
      namespace: archivebox
    type: Opaque
