---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard
  namespace: archivebox
spec:
  encryptedData:
    wg0.conf: AgB4ZeQZ75epUbSivpgOgve0FtVls7gCwJWOOyc6ThHTEiAGnH1S4dYceuOaElKZff1p+6S9NBsdWFzX8Lo72WCc2kjPkQYV7AI93sZpPgAqGZFep7tl72F+UGZhxDINIKgK/EKZzfjZEzHbDAxW1gddOCp9elOTsIhOSgEp3/SGfUv9K//Mk969Nc9/rDsHGGKGhM/wocYYm5jZCOy8zZauTQehTCwWqmqyRCoI45lRNxutP0blm8c8wGd8FvpIScmJWHbaqQTivc6FlH7vjgWSeEGzEK0+ngerHIHwQyTGJYavTqX5hKLWJCe4PozV+4rG9/3QRqWStCwNlXATprRszXjuTNXUk9Q7Zzmm/DYv7hSm6USYRzrcOlt1VCPpsC8doCVQuDyNeW1s/R66JxLZCDSCk31Jx9E2K7zuTx/OkU8QJmeqVDNw2Yu1+E5hrYNV0uhzqhicilONyhSsjImKtXAsntQmwmheF8VrQ4r16i7egFqNvBZw7K7neJ6uHjLjnfSOSLoQ7+nXwu7TEEkpzbadtsY9U9cDJ15vA3wlWiYL6Xvqzsv3Ne8/2lAMw6xHWQaO7E8sjAVgkbDcbWL1YBKfkNTwLaOYLKedta3cJaJm1rpnJJU3cxxSN/AC8da6DrbFrVzcDoiMm+b22v1wt0HCHb5wQO3jcANwdDgJwkdnLAplOCyAK2HjDoNC9L9MOntqZpktMlBpFi81VJ0P36vdOUGEJCyqgi1FJ9N+3SP4MchOapKLPZuhcl2O92xKb9CmC/34RkK8JCQIQfSD88yRJDk/T774caoh8fTwPy60o9jr8t/wsFRp/G4S8esf+in0GWd9jghvmPKFje1BZCC5RJy2QJcGq77xfwDfWCDFO4NIGoYaGyNIc8ZpsyaW6TXDMj8HF0C/eSqVmZ64i1zIfgMTMuGropAgSDaSzIkqNCj51pfu2fGbE7Z5JU74REuYQ5ZfNKx6/gXEHNgCdnAwItMoUzEacmlPEZbRlhUeSeHFvvyk+T+BwITO5Kimv4PoiZ1PgmwxyqTe5ksdj4egMe2nMKby9Enw
  template:
    metadata:
      creationTimestamp: null
      name: wireguard
      namespace: archivebox
    type: Opaque
