---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard
  namespace: archivebox
spec:
  encryptedData:
    wg0.conf: AgDc5XabqfFff8g/IXvbFzBSn8YXIrsOW8StKML0CG4dMbgOZkn+WIu4CBE4WVhnstCNmCMWJaE1CHysYjNIbCXWsurCOnYluksl6A0YI4vRBeGbAa3wAA+wdcic2vsNpQva2ecumiEcWZJtzuc64ZpB9wUSQ/k+yPY+fIspy2TA/DP9Ygzwuj+ybz14o8AVeytf9RYDb36fiQrJIAskam5lcijrstdfZ723KjAICQGxFLJujSMfTbJNIrqilPVaD0IPYLEY2aQYLQy+nXIwuXzblQH/UfVc85tMBaBQ1mOFAu0DRYOJ2es8VIjVTO0GBFjxMoJWoKdy8TzGBpfzOkicuGjzXlb4HsEwprJNaaImi9PIb8mog/h+234r6ZRhz7pyYyjvzCDcssCWChhnQq/hlf5YwyiSB9ZhqyXzzUulg05Sy69GsnQvRucej8sjIznRFlmnHH2peI2qpMy8W8Y/vXxxpwZzaAXrVnVCbOkWoPWU2cM7/jGTbXh4IHOpt8jUXAxvde++bGBjrGvuC/AycNV2o9Pnfz3dJISniJcRyQ31Zcbp+mOeGc17bSrbRQJuSjvVT0zbSdYxRfxNbLPNywuFkxLhkfAdA8Kj0rk/CmjhVD4Go7t90ZCnlEPLTsBPQhDEO3cDnXlspgjgJo+WvYN5bDBTPn/m7gohmmcvEMqcoAmBXqQvHYxbSFjwf+dnqKKOLeNPp1GYuUQuJNOTnUIfUcMs7sVkLTb/GQnK8pW4tQP6ZNDiM6vyumnSIPaHDHXBZpupWjGz8rxlGSsiCg8kmqiEZs/MpvPOjzI8DXp/3CjXw1YQlhyrSbw8YY1H7RKdgQl4rfzniCVCNiqRRMQgVRN+A+sX9UGr0QZabGXCqmLZ6bXXBxfmGhuLUN1l1AWRRVd1JNJ7QX9W9E9N/AWcZ6z+W3QbMFPLl5bBRsjsluIiiImom4KiZBOEPWtdqSRogGBrV7HMVaYNhGudbBYzMMla/QIhGS7b0ICo6+2zbX+ia7L9H+hazSfnK2yYTR+14PleBjItHp46REgVrr+oxjhwFagfIHx75ColqtXPif7SkKUtM6Q2uhAK3zlOmPg=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard
      namespace: archivebox
    type: Opaque
