---

apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: sync-secrets-backups
  annotations:
    policies.kyverno.io/title: Sync Secrets Backups
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Secrets like registry credentials often need to exist in multiple
      Namespaces so Pods there have access. Manually duplicating those Secrets
      is time consuming and error prone. This policy will copy a
      Secret called `regcred` which exists in the `default` Namespace to
      new Namespaces when they are created. It will also push updates to
      the copied Secrets should the source Secret be changed.

spec:
  rules:
    - name: sync-secret-passbolt-mariadb
      match:
        resources:
          kinds:
            - SealedSecret
          namespaces:
            - passbolt
      generate:
        apiVersion: v1
        kind: Secret
        name: passbolt-mariadb
        namespace: backups
        synchronize: true
        clone:
          namespace: passbolt
          name: passbolt-mariadb-env

    - name: sync-secret-n8n-postgres
      match:
        resources:
          kinds:
            - SealedSecret
          namespaces:
            - n8n
      generate:
        apiVersion: v1
        kind: Secret
        name: n8n-postgres
        namespace: backups
        synchronize: true
        clone:
          namespace: n8n
          name: n8n-postgres
