---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: keel-webhook
  namespace: openfaas-fn
spec:
  name: keel-webhook
  image: agrrh/keel-webhook:latest-v20230528
  labels:
    com.openfaas.scale.min: "0"
    com.openfaas.scale.max: "1"
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
  environment:
    APP_CHAT_ID: "94120622"
  secrets:
    - tg-k-devops
