---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-alertmanager
  namespace: metrics
spec:
  headers:
    accessControlAllowOriginList:
      - "https://alertmanager.agrrh.com"
      - "https://karma.agrrh.com"
    accessControlAllowMethods:
      - "HEAD"
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - Date
      - Content-Type
      - Content-Length
