---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: reflector
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: v7.1.288

    helm:
      # https://github.com/emberstack/kubernetes-reflector/blob/v7.1.288/src/helm/reflector/values.yaml
      values: |
        replicaCount: 1

  destination:
    namespace: reflector
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
