---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: binance-bot-testing
  namespace: crypto-stuff
  labels:
    app: binance-bot
    env: testing

spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: binance-bot
      env: testing
  template:
    metadata:
      labels:
        app: binance-bot
        env: testing
    spec:
      containers:
        - name: main

          image: agrrh/binance-trade-bot:testing-20230702

          env:
            - name: CURRENT_COIN_SYMBOL
              value: BNB

            - name: SUPPORTED_COIN_LIST
              value: >-
                BCH
                BNB
                LTC
                SOL
                XRP
                ADA
                ATOM
                BAT
                DASH
                DOGE
                EOS
                ETC
                ICX
                IOTA
                NEO
                OMG
                ONT
                QTUM
                TRX
                VET
                XLM
                XMR

            - name: BRIDGE_SYMBOL
              value: USDT

            # - name: API_KEY
            #   value: CHANGEME

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: config
                  key: api_key

            # - name: API_SECRET_KEY
            #   value: CHANGEME

            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: config
                  key: api_secret_key

            - name: SCOUT_MULTIPLIER
              value: "5"

            - name: SCOUT_SLEEP_TIME
              value: "1"

            - name: TLD
              value: "com"

            - name: STRATEGY
              # value: "default"
              value: "multiple_coins"

            - name: BUY_TIMEOUT
              value: "0"

            - name: SELL_TIMEOUT
              value: "0"

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
