---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: binance-bot-logs
spec:
  storageClass: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: binance-bot-data
spec:
  storageClass: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
