---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: request-headers
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: whitelist
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.40.0/24        # vpn
      - 10.0.55.0/24        # lan
      - 178.170.198.0/24    # home
    ipStrategy:
      excludedIPs:
        - 84.38.180.136/32  # gateway
        - 10.0.40.1/32      # vpn tunnel
        - 10.0.55.1/32      # home router
        - 10.0.55.101/32    # home lab
        # Telegram
        - 149.154.160.0/20
        - 91.108.4.0/22
