---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://8gears.container-registry.com/chartrepo/library/
    chart: n8n
    targetRevision: "0.8.0"
    helm:
      releaseName: n8n
      values: |
        extraEnv:
          WEBHOOK_URL: https://n8n.agrrh.com/
          NODE_FUNCTION_ALLOW_EXTERNAL: lodash
          TZ: Europe/Moscow

        config:
          database:
            type: postgresdb

        # NOTE: Those are packed in external secret
        # n8n:
        #   encryption_key: MyEncryptionKey1
        #
        # secret:
        #   database:
        #     postgresdb:
        #       host: host
        #       user: user
        #       password: qwerty
        #       database: database

        persistence:
          enabled: true
          type: dynamic
          storageClass: microk8s-hostpath
          accessModes:
            - ReadWriteOnce
          size: 5Gi

  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
