apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgBIit5CJZx0VOrmLUrx/1Ki8YVGDaAeWWp/WUqVAEyQl0SdKDtPAvrC+d/usqXOlbKsIcAbRSzazMELNFFlYH4e35aWyhWB6lNBztu9zxoHPjliQjfqklmJpWDgboAWEcZsQQbx/QKIPa1wqUl6dkUphgox6dnWrblANN35edBytGeqnqwU74IwZDpR7EWay4QXtyrprF745gJXizPs77ey5ydo15CQwSXkJ+Cn1ZIlNmSIOM0wj+aib2/pdOi1xm2EF6Iaitj9H1KCNch10yNVS1/it45pmarsfnDEuYok3azF37afZBx2+2a2fjGFLnJnU+NxdjxSx5MJmIyvR0lyRJjiOfHOoZNm9SXcTMkUHsNZLY8F8/3uWxP0iydiUmYwr0XJQo0KcI8h8EoENI4YwxaBI8hNUbi1PrW1ARCb3mfaVzU/bypn893Cooo8OkSa0mdjUpzyFCcAEUkD5SnyPspzFbwCWKCmryKxYzHNoaM2tScMnwhNAICpPAevpdjaIs+2emMrQNXnhNT11WmwHEpr+JSxiialIix0k9eCa1YR/S1h2rHdRM7EiMxb3zFjhWrbahIe1uYxJqNmnTQPnaMD7HrVtWhRbZSgXNXa3s0tkas6kVhgNYp4nScIeR5dAoV46nJ21oTld81NpPrws8cop5Kiqo1LpRFxTAqWv9ftElI7r4yqX067dN3HCaoKm7zswcPnAs9RfWgrS5fl
    secret.json: AgA3DF8dZklqJTPS3KjZiU5WTNf2Q/8cySwoo1fnEbIsFGsSYX/qIvSlSNsAMTzVS4KTRfyrwLxHKZYOKRsa6Fij5mc8DG33tctbPB1v5OkEW4Ri664LMsg29z6jlUfvc+lWLsypn5Ijumpf/Pj7eqsa0x3GTwhcxiMUJ5OV0k7YZ+OXfNjA8aXsrf8xGnsFpow19AEmFM4kvguqk7jYZ5XkTC/Y19hGwe8SrCWI/sWE9lrITpwnqKy30t1W1PbqiC7tCFEl/tD5d2QCO4X4xodHZ78kU+O0ZiniCu454iiM7IMo89sva+raTxoQq+Ve4r1AKkinQLNafvKZqLN8j0P3ntOmx3WCeFIj0YNf15UXOzbKlP7BOMrKrrW4oRIf+DU5Ng6XOwwv+A5SrhbFUJKWZ5WqjAKxZvU8GJDUNk1O5B9M5jFpG70kEd2wHJje+JFHm7SWsSuGYgnWJzAfQBf54UBhR06nbuHKp85/3F3yJunJLYogX6ta1VIFNNmNZt32VI/YVO+HhhDO1nwhU++veBtAFdBQi9vBwdxp5llN0oVIss9sTSl9Dz7inTxLxwRMonXNPi4aBO8HqbsoORDSwo4/IHGjxJnDGJwQ80NgJ3wF2YlG33SrePP/bzjErTL/bS3JY9MSw+y3UYtrTPupDT2QW0I5Wpp0Wgk5QNBe7gRHtokr4q4WDovqQmZ35pn+l/KI77DD8+GTH7FWXXGdxQ5jrTYwm8Wq9eYnYpwmzXiL5lRQiOL0ZPKQbneQX+e63O5Wm5HHhEX2fSIjoXlKmJqI2qK1rrJLCn/AxqV3MHi8gosIetz6aF6poGqqrzfEXRuUEMo1m806fHnbLj7sDrafSdezExtpD+7gvnymDA0+7UeqxLjQ0p/V28/06YQtao3w/Itngt7XGktlt1lFz6BrIAnM
  template:
    metadata:
      creationTimestamp: null
      name: n8n
      namespace: n8n

