# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: loki-api-external
#   namespace: loki
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: loki.rsd.prod.nexters.team
# spec:
#   type: ExternalName
#   externalName: lb-traefik.rsd.prod.nexters.team

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-http
  namespace: n8n
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`n8n.agrrh.com`)
      # middlewares:
      #   - name: redirect-https
      #     namespace: traefik
      services:
        - kind: Service
          name: n8n
          namespace: n8n
          port: 80

# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: n8n-https
#   namespace: n8n
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - kind: Rule
#       match: Host(`n8n.agrrh.com`)
#       # middlewares:
#       #   - name: whitelist-trusted
#       #     namespace: traefik
#       services:
#         - kind: Service
#           name: n8n
#           namespace: n8n
#           port: 80
#   tls:
#     secretName: wildcard-agrrh-com
