---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ping-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/czerwonk/ping_exporter/master/dist/charts
    chart: ping-exporter
    targetRevision: 1.0.0

    helm:
      values: |
        # https://github.com/czerwonk/ping_exporter/blob/master/dist/charts/ping-exporter/values.yaml

        config:
          targets:
            # Public DNS
            - 8.8.8.8
            - 8.8.4.4
            - 1.1.1.1
            - 1.0.0.1

            # Giants
            - google.com
            - ya.ru

            # My stuff
            - agrrh.com
            - w.agrrh.com
            - argocd.agrrh.com

          # Override system resolver
          # dns:
          #   refresh: 2m15s
          #   nameserver: 1.1.1.1

          ping:
            interval: 5s
            timeout: 5s
            history-size: 10
            payload-size: 120

  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
