---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: netbox
  namespace: argocd

spec:
  project: tech

  destination:
    name: funny-bell
    namespace: netbox

  source:
    repoURL: oci://ghcr.io/netbox-community/netbox-chart/netbox
    chart: netbox
    targetRevision: 8.0.10

    helm:
      releaseName: netbox
      values: |
        # https://github.com/netbox-community/netbox-chart/blob/netbox-8.0.10/charts/netbox/values.yaml
        
        existingSecret: config

        # @param resourcesPreset Set container resources according to one common preset:
        #   none, nano, micro, small, medium, large, xlarge, 2xlarge
        # https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
        resourcesPreset: large

        valkey:
          enabled: true
          replica:
            replicaCount: 0

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
