---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config
  namespace: netbox
spec:
  encryptedData:
    secret_key: AgAfvXIql7beBoFN0yqnoLVI02Pvii0QGW+3JGVUybkGQFey4fLg6Ww9mafKMIvhRJTED8GDIm/rxSgI2fk4b/wYEaAqbIHJD5v+NsPNo6/Ur3H+/f9VBu1qlIC2eKg9H+yPC1+Glo1ar9x1Alee5XaTD6/3qDOJHiNHNA9ccqdykVoBIr3K80ezWLQy5lvLebWAZO6Z5F5o1WxXSpRmizv3lZOVpN4iv4sP5E0ZrioI+o8PI9jjPnNMaA/jQmB5REfvEoLswO4K7bV1WOGAoaFa/00BajeFo1CRajYh7//vGIEgYOzVMKii10oerN2OjLzZ2bfjjAdR7jtdKX5VtpZoIxH5AMK6CJRN6rt9Ir8Efnx+JR6F4Zq+xHTLjmJweHjwwHTqyl+VXVZ0i2pLBK7fubMMe6nb5YY+TDUdBcAzIoIQwlsWMPVVM//xnWp0hUZEppzDId9Ye0ggz5+Xgn9OIsjtaj4Nn4fkBcKITQRZv5Ao5SC7n2JHc38otK3RYL1r0hET54vpy4Zt40JnHf4zJJhLYCiDndzZZg7dhlY6nbn4YNIZv6jdjkbNH346hT/ePX+9g8J8PwDJ2e5qLK92I/oaYoFLNqkppSrEN40wgOjoLLisHShTdDntRgIVls+O+VSucdYLshnqxxHurn1UE/Nk8Ts5GtrGR4+P7f/u7+bketvIYqIA5J3l6R6wuXQyaysFGu9T8AnDC3iIHaB3oLIPIfQc7D5qIXs+teSji2dhDVJ3yyblaNZ+vAVd/rrcxHjefN3nH/3KYzPYjB+XpuKM6+farkGCR+6mGvlFNxIsQWdUnedw09NfPHY8p9roNVslt4G/ch3CGh+oX1MGvs6QbCAL9Vs6D7vc9+TH4ek=
  template:
    metadata:
      name: config
      namespace: netbox
