---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hajimari
rules:
  - apiGroups: ["", "extensions", "networking.k8s.io", "discovery.k8s.io"]
    resources: ["ingresses", "namespaces", "endpointslices"]
    verbs: ["get", "list"]
  - apiGroups: ["hajimari.io"]
    resources: ["applications"]
    verbs: ["get", "list"]
