---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: metabase
  namespace: argocd

spec:
  project: personal

  destination:
    name: funny-bell
    namespace: metabase

  source:
    repoURL: https://pmint93.github.io/helm-charts/
    targetRevision: 2.27.2
    chart: metabase

    helm:
      releaseName: metabase
      values: |
        image:
          repository: metabase/metabase
          tag: v0.61.x

        timeZone: Europe/Moscow

        monitoring:
          enabled: true
          port: 9191
          serviceMonitor:
            enabled: false
            releaseLabel: kube-prometheus-stack

        ssl:
          enabled: false

        database:
          type: postgres

          existingSecret: postgres
          existingSecretDatabaseNameKey: database
          existingSecretUsernameKey: user
          existingSecretPasswordKey: password
          # existingSecretConnectionURIKey:
          existingSecretEncryptionKeyKey: encryptionKey
          existingSecretPortKey: port
          existingSecretHostKey: host

        password:
          complexity: strong
          length: 12

        resources:
          limits:
           cpu: 4000m
           # memory: 2048Mi
          # requests:
          #  cpu: 500m
          #  memory: 256Mi

        startupProbe:
          path: /api/health
          timeoutSeconds: 5
          # failureThreshold: 60
          # periodSeconds: 10
          failureThreshold: 1000
          periodSeconds: 30

        livenessProbe:
          path: /api/health
          # timeoutSeconds: 30
          # failureThreshold: 6
          initialDelaySeconds: 3000
          failureThreshold: 100
          periodSeconds: 30

        readinessProbe:
          path: /api/health
          # initialDelaySeconds: 30
          timeoutSeconds: 3
          # periodSeconds: 15
          initialDelaySeconds: 3000
          failureThreshold: 100
          periodSeconds: 30

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
