---

# NOTE: https://artifacthub.io/packages/helm/bitnami/mariadb

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: passbolt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://cnieg.github.io/helm-charts
    chart: passbolt
    targetRevision: "1.1.15"
    helm:
      releaseName: mariadb
      values: |
        image:
          tag: 2.12.1-debian

        mariadb:
          enabled: false

        persistence:
          enabled: true
          storageClass: microk8s-hostpath
          accessMode: ReadWriteOnce
          size: 512Mi

        passbolt:
          baseUrl: passbolt.agrrh.com

        db:
          host: mariadb
          name: passbolt

  destination:
    namespace: passbolt
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
