---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: kyverno
  namespace: argocd

spec:
  project: tech

  destination:
    name: funny-bell
    namespace: kyverno

  source:
    repoURL: https://github.com/kyverno/kyverno.git
    targetRevision: kyverno-chart-3.2.7
    path: charts/kyverno

    helm:
      releaseName: kyverno
      values: |
        # https://github.com/kyverno/kyverno/blob/kyverno-chart-3.2.7/charts/kyverno/values.yaml

        # NOTE: bitnami/kubectl image now uses :latest
        webhooksCleanup:
          image:
            tag: latest
        policyReportsCleanup:
          image:
            tag: latest
        cleanupJobs:
          admissionReports:
            schedule: '5 * * * *'
            image:
              tag: latest
          clusterAdmissionReports:
            schedule: '5 * * * *'
            image:
              tag: latest
          updateRequests:
            schedule: '5 * * * *'
            image:
              tag: latest
          ephemeralReports:
            schedule: '5 * * * *'
            image:
              tag: latest
          clusterEphemeralReports:
            schedule: '5 * * * *'
            image:
              tag: latest

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
