---
# Source: baserow/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: baserow-redis
  namespace: "baserow"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.14.2
    app.kubernetes.io/instance: baserow
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "YmFzZXJvdw=="
