---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: vector-log-reader

rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
