---

apiVersion: v1
kind: ConfigMap

metadata:
  name: n8n
  namespace: backups

data:
  dump.sh: |-
    #!/bin/bash

    set -e
    set -x

    pg_dump --verbose \
      --format=plain \
      -f /data/n8n.sql \
      --inserts \
      postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.n8n.svc:5432/${POSTGRES_DATABASE}

  backup.sh: |-
    #!/bin/ash

    set -e
    set -x

    mkdir -p ${HOME}/.config/rclone

    echo "${RCLONE_CONFIG_CONTENT}" > ${HOME}/.config/rclone/rclone.conf

    rclone size yandex-disk:/

    cd /data

    # Sanity check, at least 100 kB
    test $(du -sb ./ | cut -f1) -ge 102400

    restic \
      backup \
      --host backups \
      --tag n8n \
      ./

    restic \
      forget \
      --host backups \
      --tag n8n \
      --keep-daily 7 \
      --keep-weekly 4 \
      --keep-monthly 12 \
      --keep-yearly 10 \
      --prune
