---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: n8n
  namespace: backups

spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      backoffLimit: 1  # restart once
      template:
        spec:
          restartPolicy: Never

          initContainers:
            - name: dump
              image: mariadb:10.6
              imagePullPolicy: IfNotPresent

              env:
                # NOTE: We're in backups namespace, so using cloned secret

                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: n8n-postgres
                      key: user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: n8n-postgres
                      key: password
                - name: POSTGRES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: n8n-postgres
                      key: database

              command:
                - /bin/bash
                - /app/dump.sh

              volumeMounts:
                - name: app
                  mountPath: /app
                - name: data
                  mountPath: /data

          containers:
            - name: backup
              image: agrrh/cider:0.7.0
              imagePullPolicy: IfNotPresent

              env:
                - name: RCLONE_CONFIG_CONTENT
                  valueFrom:
                    secretKeyRef:
                      name: rclone
                      key: RCLONE_CONFIG_CONTENT

                - name: RESTIC_REPOSITORY
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: RESTIC_REPOSITORY
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: RESTIC_PASSWORD

              command:
                - /bin/ash
                - /app/backup.sh

              volumeMounts:
                - name: app
                  mountPath: /app
                - name: data
                  mountPath: /data

          volumes:
            - name: data
              emptyDir: {}
            - name: app
              configMap:
                name: n8n
