---

# NOTE: https://artifacthub.io/packages/helm/bitnami/mariadb

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: passbolt-mariadb
  namespace: argocd
spec:
  project: payload
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mariadb
    targetRevision: "11.4.5"
    helm:
      releaseName: mariadb
      values: |
        auth:
          existingSecret: passbolt-mariadb

        primary:
          extraEnvVarsSecret: passbolt-mariadb-env

          persistence:
            storageClass: local-path
            size: 5Gi
            accessModes:
              - ReadWriteOnce

          tolerations:
            - effect: NoSchedule
              key: agrrh.com/node-role
              operator: Equal
              value: master

  destination:
    namespace: passbolt
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false
