---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: tech
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.5.2

    helm:
      # https://github.com/bitnami-labs/sealed-secrets/blob/helm-v2.5.2/helm/sealed-secrets/values.yaml
      values: |
        # Must be copied/created manually
        secretName: "sealed-secrets-key"

        tolerations:
          - effect: NoSchedule
            key: agrrh.com/node-role
            operator: Equal
            value: master

  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
