---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-provision
  namespace: db-personal
spec:
  encryptedData:
    password: AgCrpN0kejY5LHELKYfWK1EgTuSlcE4Z3h6lZ8N8Fl8eqjI6ZhFUFFVkDy3bsSp5vIu3iMeprjSs8ETFMnhRHEqKpjr7vqaMc+7QCWXomzdzwOk7Ha5rjlpMUWUbh+JxLXvBE3fmZ1DLdIlK8bS09xun6QG7mvNpTJIqLai4Sl+mXe+l9d3QfdCmq6s3GId2HMlBNnTx7wwzaP1KeRuFOXVx1lzhsslOVpQHYCpPUIzwIsRxHO3bxHeJ3AimT57t6Acy9/rQTYFpc7W+rOyYikiqZXF3gy/0hSWzx07hbyS5Y3HfMy5asouiPEpKS9RZ/NSJFu7S8XT4J1Af13jWHUrRnoEgiYInyawCLT8G/GERdO7F/UMigs7NwrE3J/9QoShC/vYSWExzDxAuXxJZGRNoPxgQ70Hxsuro5b98toY3vRaQPrKTSw7TPXzCJYANvjNLJKyzRrX/hmXobM81vnLm7r/Gx5xf1C+8wIvFYezGIJptTqFB5viPF5ncQlVzRy0819xwdUNHcUH1k8jrVFVXFSIbXig3l3a4gA2HI4L2V8gWSaZHKyYZ5Uvxytcs9Pl+vzCUV77ihpI2O+Nq1kPt5htbYOWiUXziiNh9u+4SDyR82yjqq9p9RKYHjl6XDrEMB5Ogmt5/tWkZbYFSUEyx6jUKLkMP3nzsxCEa9BgYUG80TUYH0PcbRGaATLdOXubFEnBFlIjPeBeaGZ/BZtS1MTVEDbnL5ew=
    user: AgAYcruWo5Nhb5C/r42J6hoS6/aiGjiLGcNKqrZG0tsgr6oIfLdjWugY13CGkZSRN3RGuF7EwpO3zMqLoHUHbJEEVNh2FQyLDOe7mNo9E1A11JkAjhhMg7A84UdZ7If1JXv80bo2RF9EMfOK6C7suL6FK0J+q2V71ansvLaBThY//zzKpt31KDBajpVc0mMnT/5pZlJGVKsBVr2k6wikdkcr0+wyo1bg65+xcW8KVBoUUZK9huJDUfc6TR4w6VRMLIXNB8L+sWNtsBk/OJHLV0zMOIJsi4zdcDk3CYv2hFAM4U63Cqg1q6cpAgd+sgrlChMasLNeDIvho5PF7/+ZUKGC3K7c0l3baZNFvx9LQ+x0g8FtKYmxdMioYWfMjg2kJQhm6BlV4tATdzJ+tV4jrEhoG3Tnep7jhXxjlLgOT6Uar0zjDUjpkSMUY3LmU+oQrUMhfKri5m7aa2VySmqieMjRZ2M6DbXD5OrEkU1YZDFL6RZKV+zV/83hxhv6mVDOb6Ewi1WGvFCO/qPP44NPZNkLXdrSDYfyRDnTcPQeonM69cwlkjT5VLPIfzFRy0/KIy9u0Bdcegw3fVGPzzuGmIEXmDevd+eoSty6iWoNMTCcYHOU/M03joVro2C2UmJBfzJ89+0xv/6J5ug4xtNm937qPowhKZszCK27rczsQli6zMUV1pV1wmaH8xAWBAtsxDivLjriwrmwgSs=
  template:
    metadata:
      name: postgres-provision
      namespace: db-personal
