---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: provision
  namespace: db-personal
spec:
  encryptedData:
    password: AgCSaS4rfltTSNKqDMVxdCZWtGD0vpDEpqHY7DEEmxazkM03YU04a95aUpmWDG7NNdmd908sV05t21xgJNsZZOioGB9PfbzOJVKX/qBO4ETqv+Q7cbqZYxEvEEH4tM2XJ45avQrR89D+OCmYnn+8Ukoq8xkyKUi+OWd/p2EbKi9xO8jgGqO0/qxE6qXcnIi1uyczN9xL47ZpzSClh5rztOLQBFC68rlFjI/ulU/HAZIY032YvGK6kwOgwaDoU+e0oOypX2g7apNrvyTb+QvlDvRaealuR3BlH3/it18rxKcMFKjY4YgjY42rqlLQb+BBsXIn09aaoGgD4afkBHBgUMMRvZJPD+HhCAwF2KVj4PywxXdJB4jgs3nsgXEFzD4zCTIyb/RpmanwTiCaVWwoltjCdKRpecyBPsksU+3vbCqqn8izcz/0JVk6E5T9aJRQzlloh1KqO/rphnZ1U80UNHN0iMFzb3uGkUuESoX5BUrtukaOUlo2oTlyaxIlmRY3u3aCh5rIlODtfW+iVjv+K78HjAujm6umvdte6AFNmUEIilZhd1ZFv9bwcN4jBpX0UjNKY3W2MDaOVikUBJsuWaktMj/3X7mXkO9kALCyDeg5HYAKJBo35SYMSigoSqFAeOCuBK8dcDq4Qeh8cYFrOVkumh4FEsUVXhoJgcwErjIshoXpnHA6KTW8i1t9jSPcDgVknLwsJALVzKdX79KNFEO0azmsoO1vfyM=
    user: AgCQ9gcZvfqvcLRDFW5QT6sTFNWgb20IZmP5wQ76Eoopvbi57f3E1H7wn2OhhT6Ab81at9rnxtdXmofW7KotBw7N2lBJ1Gm/iJ631GB5f2A2uah/USy+asqA4hDO3X1IHu0bXzFIcHZTy1/oKMEIONiNJ0v2DUxLRz6BiCqOW6ByT/3dTuBZTzyAk84GqI0SmyV+JIGfHGI+9BMEAufqu565fTAMhfi4ob29UjwJWwkDTMYsEeGyN9aKMNaRZFF1+JS6US2rwrwOzuvVI877tjS5Akn5GaX1zMXD4qLF35w94V4uUEyGUgEXfv00bxezbB6M0PecL+2WYEzpviDDk/aWCd0GdAspzhHR9F8PARWQ9RygNXgEykYnpaedZ+tUBCJeDY+Hjys/dExHF4aRYgIJHVCOqftLPaLO2OPQzDkapxVV6hkgO69SIAD9pnnqL4O4hlEp4gw+7ZjO/n8jbP4Wktow1jcjaz40gdforGtbEXMkRcwD5FbvWGIAhCjFZL4/TI9V7vsSgkXstczUdhdxWYZFdBHKxL5Jzrfp0R7SsrqRv0zxjVpWenWtD99uuSUxpdL8wBzWC6lxlz9/8v41DzUaQAX0g8GRzP0CK53W3hQ1Umacv6UT8MPJNIeT5MeiAEkjEqn6H0jPuEF3g4/yUCPJ0KH7GNNvNZy+bOrpmzoNEwiYtHQlaC53STKk8vlj86aD4zlePkQ=
  template:
    metadata:
      name: provision
      namespace: db-personal
