---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: provision
  namespace: db-personal
spec:
  encryptedData:
    password: AgAGBY28cxErxRI75v7WTLL42uWSF2/BwK9pNxAKezWKSbj3wICLWb5U3gjcGLF9g24cOhCOsi39JLkrsnDOkLac7oghiIZG9XNa/MuxVWs/GsvnknBQsU62zG3M1N+yyZjtLomqJpo2b5Y+imtEOy6VqRZgzO2gG375eqj86A4+f9gzZFPvAWBgF0dsgRedEEPBt1miUzrMuKOsPVoxZpxvshGiTNMPTT2blr95HLfha7MyGhA8F6QQXZmMH3C2osZJ3ovlqU0OrVi9pkneQayoGVsHwsG4oj+ju1SsMerDZaGhyDLpZrEqVCjaiyoITeIXjMfwS2H5A86EcEMJqIYCYomO0Ji2peWZfNsHTNSRRDudvSfb4c0wNbemPzkPzYv50r7FsIJM4jw7kzKrNrpB4MfvE/zegBJX+bauR8H4he3koHCeN9rGxOFaGkrPZdTrPGc8DjyqstNfxaJU+78tI1WAf5qXd99sZ48IHDJoefZG3R2ILGq4ZhGqQ9h4pHBbz8gnGjNMEoXlXbrftg/A2HCN8rcG9vzGhpDuMfHT1XtZSA8DYzSu1pPM27Tygk7NHN8ELqGUSYs6AhFM8ltd8UB3LzNDhVJeaI9hdjPicMRQWvOp6g77Irti/r/dZfC4iyLFRG0WqpqTAaYgmkgIi+4HS+SwrYPoRb+JTs3nT8C6/jVFQVulee/CjZLK/crD/6U1YnR4t91T1kxLU1jD8x9s/kzLb6Q=
    user: AgDI7YeGczITY9xsfjD5sa/njPv8p9pA2zJm28kHBZqCR3ohpIVOwJjALs1rJkVwMKdBH6urhu/q1RfjrgV2NfjIDjV7mr6HRH6pkN2Ckeo7t8KZKVU//LhdtRGK5UzMABdO6jWjiQixykx6DQUMCHFh5bx0/auqyARkWG2Yepw0wPEqZJIIxd3HIW93l5Xardt84s631Q9VYnNwrqo7/KKwdeVcqoNzKpB+VbhX84cl8DIOLyW5b59geokk4/ap+UsNzU+J6PtZWLLlfV+qAuCtBx52B2RViGaac5T7MOftl0h8V6noVSA4nQvsSmJ/8intQv2aGAtV39At0CWWhgCQ18tQU0t3VYyJZaqs2n2mR/T8bMoQdiVa6Z8wz0fBEBSLlE1/8Jod5FSNNlpayZ6H9AWtUYauFiYZKTfqy7TCbKnX9qlVB9DLLWVvm+ybP5E6NIPqBor27XJ1SB8XNWw4+YahyrHki+HN9sX8KCtC+VvEISg+iF8561hpQR+rs5cg/tPhJKPK8Ou5XBKBGAHjSGG5ar6IjS76pcb5ndg0DOBYW1SWC2Gp5f99OuxQJsPS0KmWdU/kdWCVArf2LPXmUC1yUiiBaPWmt/JLRmz7VnJAjuapIFuhRBCPsgusD/qAoQbqZ52NoOdaMJ0dl8WvAI/lgmPdo0QbG6Q2n8AAE5g7cTwGE0tc6DsAIC3+DguQ39JTQ/Dv+Dk=
  template:
    metadata:
      name: provision
      namespace: db-personal
