---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone
  namespace: backups
spec:
  encryptedData:
    RCLONE_CONFIG_CONTENT: AgBLhTMO6jQcKslyplMH3Rsk8+Z/i4XwdThSNwRXgNtYzPwGTUaOwAVU49ANvs19T0WQpM5qlzbtEn+wfYBlV61gcV0hg4iqoOqZnIzCt8bGwYgmlRlx+NT7CtWORHpE5QJziZgKzskZPU8FO3hg5VuWbLQE+mu7lUw8otenbzwXWkDJDaxFBxzHRYoGzBSHivrpxnAb8pCLQriMlzhAY1YE7jifUMIZmn87DJYqvoLbcOE11ZBCSyX898VbnZGrLpQx/uqG5FRKGLLXr2s4iOYgQUQPl0WvKuDIach6OqJrdE++oLpUuaT9tKwuCFbQtms/9dyTNJRuA01Vq4Cr2T7B7Y0REfuJJ34SyfxNNc1TbCd4l/9xrR3xnWVKfqTpDlnfRhPpeyYfrmWzOZkl42azucjCXfpbdje//lEXtQbtBZsu8DDb1YcXsTsfRletsGsB0C8PYLMv9a9GmvEsoZLbzGs2x0m5Pc/VvyegRzsi8VBEiJTY/O0b3NhQj/Suo++B/JwiFO2xlurzq7NI/dYrFm8bdTR3hTRt0VbK4fVyZ2+ZtvH8KBFdXIhMDbiWtunhgbBbz/Dqe4g5bDGjRt+R6AKh+/5YKVlBZEblBhyV7JQfbkJXXVvvG1D/+pqxoJGiwdW4TJVyF8v9FxALnbA4Q+enea2aYRLALhCxX7eK0biBdTFDZ/X7JeSjxJ+v3YP2PmkthOyVUHRpcRRo5A9IQXmedLa9EK3s8jU0ZfiLmdSrwev3G8HofCUzIB3iIU7/MJX+3UbW3X9g97HU812gIrBjZ44Q+97vXn2quqjkcuKtEtiHb1pU0Fj2p2XPteyqLOosyeG+eD4wqLqD3SGFaCKvlLzRH6b/4Kn33Yeb/WuCCEcdf0x3XZ82fhoZhLB7+OSSuCv7Y+c79GL/LH75kI14Oz+avEXpaIcXaVWfChdWrljMbawk/Ek9mLa1YPChOZyrY1VBV/lk1DhvXdDO7yBdsYYfqjV2MUkcvbRD7MtsnJMGGkWPgMXynUIEvInkTrVMYrTm3XuhabcvboJBWSWhIpcILeVO6jd1X9GOp2BmKvCZkjUvcmF2yYlvwgihnKxuwq2RBcZBIw3ViFhXbqi7j3PF/MFjGhy+pysuAnyRQrMO
  template:
    metadata:
      creationTimestamp: null
      name: rclone
      namespace: backups
