---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone
  namespace: backups
spec:
  encryptedData:
    RCLONE_CONFIG_BASE64: AgCuL9mEJVJmj4hJiAASnVmO4wZsn/TzhNRSctgylEO7U0kBYKUfo1fTc/73W0WrtQ/hU60Juqr88Wwzun3NXtYy2xzOo7WaAZVMY9iBfRblwo9WRu5lLvLdmlyvSb4w8wNVlLQK9ftwym2/13h+QqLYCEK9A55aMaOjQnwwu0Yr/NNrqr8USdZvRpukgLyiKgJ2dr1+L/3AOvf9N6RQPd5yrNxfH6SR5rBlArr3zl3PUfQKydcrLrLo9GKnZDz83B/5yChpokaktkOrJFxVQN167OtBQMENjbg/kb6/bQv0JfwKWD84Biu/82QoHnB9QKv0SsoA51f6v4wGOYGb8gGQp3TTAsP90qNKGX0qsq7vnzp7Xrh5xBqVxton36Bpwy0WaLQ6mycdnq8cjqK/7wDZYx2QNf1eb9AVY75N6JHfs2wK93yuNTR73KEnZN6UpJsN4P6gQ5L1JEuwFWSNxF0ffknrsXT7Qm9VXPvYHBJBRbyu0JebPIN8ZjV0YllsZLFSp8SvcndkwsRsruHAuoihGGKyJ3dJNJIFeCA3VvnRUk7h5yJeiheAx+pMkaJGpshr7J8+H5X6KOVfdLL+uM7WXHSH6OvnSAUDP0Nls7SwHntJBVS2IMxZSwNBJ/GPe/mcr8AZdm8bMbsk1iCU6j6n+QMjtITUC443w1QLxRTcfR4aQH+5+EhcTVclk5QctvLxadCZV3i77659O7pjHqUjSS1JftQHO/FYJt1M4OK1mBNPBU6dbpgvT477LH16ulMgFUlKbRucmB34f7Cw2d+uW6VyTWqoUjpgEU0zBfrMakEs9jnQiPEsgNj+gntKd9zadh7ABcFyhX5WyCdqXKDVpALr1StjxxgOg3MbQFWMUABI4nxs8ZooxPb3T1s7xBVu0MLhWdP3gmjC6ERgxEy9y/ntK01Iro/xj+it8aD6dkVQb77DeG4RkNALJpCQs6wdt4g7k26MFWEur1sqb/90uTjvTqcqPRGq9veV4vKdHmn+FHGFqas0mdyOCAhZVNfzChaefrrxGqok6KJKjDmtpBli16UBtK9mo9eQ7XKPAnetdln7soslw23H5iFCYAKm0mVq5mzFqsEeuqNZWnoZX5thGU/Yk49GP6xa3W6dZ16V/jE=
  template:
    metadata:
      creationTimestamp: null
      name: rclone
      namespace: backups
