---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone
  namespace: backups
spec:
  encryptedData:
    RCLONE_CONFIG: AgCNR7Y/oqmmy/HUWusZhZeFkrO8Qep4RjkaUPVNwpdf7vcUxdUUFJSHeZA5RHd2OIdAOo+h91V3VJhGoL7KkbWJi8w8M1MXe2BN6i0ILV+ZZIs/TpfvXRiqE735AbFnsqDOuhiugqBhTpmn0CVLKwczpqFU9qBEWDqhbzpuLHzZroeS13HgZ1n7bcH6CYWBDgRRRJp52H6vHHAevpmQ3x9uvdRoabcXhygBWvHUjdXA24umHdzEgmbOLEOvLbi/8D6gEC8hgy+D4aiArzsal8ZG5JYLmQxKQvK8M8Y+XIvQ9rX4jtAUbLWgJmdpC15uB8oSWX1d6w/QPPseZKsG39vC6cQrYz0sViUUNqLy2Mw9mq3o50KEJYk4ddLmv9UZVQEYKctfHY3Nm9Bek+a0XgglBA3etFGP6uVul8STvQkm7JpYZIoIjWo/ttNz5jFShM8m/zSh4dtt3m7vJpLc1q7mlCF9iJDkZldZtWDe/tyA5AVbl+AxxjV651N6x9quYcURmrCRVxRliwxOhmC3gx1Xo/ltEYUr8JLyeO0BHykM6/ZbiKm1zSPU+fHPhFcIHjSzRgc03FDuZdNQPoq05opOE/Uwz17fmU4x0leTFPGd30HDpw3M4QxoLsC8XG+0cqrBFoBteEos7rXSIfqG0GgfVxcWk/75m/IVKY7MphhWzVzlbtKL4q89Lltsdo2arEnFsX+UU89ys2yZN6NKQh/JyMnNTpIdhbUvWvCzPUwEYxdVqkOpoDRq/7zVR+xerrtVd1XCmfM+DCjcpgtPAsf1abJ+UoIFnPnj3z/sJOFYnEVegFL5bsJpTqZF6cnlMyc+PDBQnVnXG5UQRgFdK4yBoghfHKfh0TxdYnd89RcgewStvxa0o3eqjj72SukGWZUfqNkRCzF2vqU6lkL6KG2GnI8YmQ0JbWG2WYlQ38xms+BBriXI3yFWqwaKBInEpHphYcqFTfKrU5lQou14rjhAkSqdlsjA8q32q11lx07q4HJXdw8VEN8suYLy1jBQQK5qvHUX6WQ8VJA1O9kuOYC8ex/KPsZUMKwRtuNz23dwPsRKs66BRlFXlGfpQf576CsZp+zyKEd0hGzmDnpFOYIxXeLEaUBmDl6aG5Ah4x5ScUeTgogE
  template:
    metadata:
      creationTimestamp: null
      name: rclone
      namespace: backups
