---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: nodeinfo
  namespace: openfaas-fn
spec:
  name: nodeinfo
  image: ghcr.io/openfaas/nodeinfo:latest
  labels:
    com.openfaas.scale.min: "0"
    com.openfaas.scale.max: "5"
  annotations: {}
