---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: affine
  namespace: argocd

spec:
  project: personal

  destination:
    name: brave-booth
    namespace: affine

  source:
    repoURL: https://github.com/toeverything/AFFiNE.git
    targetRevision: v0.16.3
    path: .github/helm/affine

    helm:
      releaseName: affine
      values: |
        global:
          secret:
            secretName: 'server-private-key'
            privateKey: ''
          database:
            user: 'postgres'
            url: 'pg-postgresql'
            port: '5432'
            name: 'affine'
            password: ''
            gcloud:
              enabled: false
              # use for migration
              cloudSqlInternal: ''
              connectionName: ''
              serviceAccount: ''
              cloudProxyReplicas: 3
              proxyPort: '5432'
          redis:
            enabled: true
            host: 'redis-master'
            port: '6379'
            username: ''
            password: ''
            database: 0
          gke:
            enabled: true

        graphql:
          service:
            type: ClusterIP
            port: 3000
            annotations:
              cloud.google.com/backend-config: '{"default": "affine-backendconfig"}'

        sync:
          service:
            type: ClusterIP
            port: 3010
            annotations:
              cloud.google.com/backend-config: '{"default": "affine-backendconfig"}'

        web:
          service:
            type: ClusterIP
            port: 8080

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
