---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: affine
  namespace: argocd

spec:
  project: personal

  destination:
    name: brave-booth
    namespace: affine

  source:
    repoURL: https://github.com/agrrh/infrastructure.git
    targetRevision: HEAD
    path: charts/affine

    helm:
      releaseName: affine
      values: |
        global:
          secret:
            secretName: 'server-private-key'
            privateKey: ''

          database:
            user: affine
            url: postgres
            port: '5432'
            name: affine
            password: onIWI4LrCQqfy8Fd
            gcloud:
              enabled: false

          redis:
            enabled: true
            host: redis
            port: '6379'
            username: ''
            password: ''
            database: 0

          gke:
            enabled: false

        graphql:
          service:
            type: ClusterIP
            port: 3000
            annotations:
              cloud.google.com/backend-config: '{"default": "affine-backendconfig"}'
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

        sync:
          service:
            type: ClusterIP
            port: 3010
            annotations:
              cloud.google.com/backend-config: '{"default": "affine-backendconfig"}'
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

        web:
          service:
            type: ClusterIP
            port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
