---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: affine-postgres
  namespace: argocd

spec:
  project: personal

  destination:
    name: brave-booth
    namespace: affine

  source:
    repoURL: https://groundhog2k.github.io/helm-charts/
    chart: postgres
    targetRevision: "0.4.1"
    helm:
      releaseName: postgres
      values: |
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres
                key: database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password

        storage:
          className: local-path
          requestedSize: 5Gi
          accessModes:
            - ReadWriteOnce

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
