---
# Source: baserow/charts/redis/templates/master/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: baserow-redis-master
  namespace: "baserow"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.14.2
    app.kubernetes.io/instance: baserow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
      nodePort: null
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: baserow
    app.kubernetes.io/component: master
