---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  creationTimestamp: null
  name: postgres
  namespace: n8n

spec:
  encryptedData:
    database: AgCLb5uDlvRAdN5FKu0xJdakKraJzlVMOYDBYaDpUQYEs2UvaThfz7ill4h+vF2XkSMeJ87QnGaXr2ZqWG4thgN0shLzTElLtKgsQeqp33tTnII5bmJzUll+gUY0CLGVS9Ch549V0SiKLxWZFVDqh6OZ0hIg6h5+DyeI2nWlLSmTVRiQXG65eNu+BP4QhtznGMXOLJmrByvqJTW4fyNND61YvwUOq96ObQYq0WAyKp49kWn3baMiYIk0BU57keukirYHT/RYbVC2cempHCcO7PfZQ1rj1bsN8szLJI9WUytjBq+rS9e7dD9RDPGjZCJoiWhe7OSgyHy/mxH8w389k6H6N3lFmrwlSFdlvAi4pwAnvKJaMqkp4b3mlrNndCIeaSjxTnikvPX9QD0dEjyXULnLD+ukD74/OUmS4lRK8ZkQzsU9mmSsqQYBgObL7zH1KJOjzAVUs/IElO9ynMeYQ5ec974/wxFiNpWaBK9HYkIrtfEfcgZKifvCda5/JUjE2D6RbsiZe8QWDSUgWpWasuqSrPqDOCVOxQUp7sf6WL8Xx9b5N/sUytwajUnzB9mcIC/d2oVWWGY7PvXLvcQPEE6UDiCaCWoMeFLx5uO0k3c6E1StWkJLhZXlJUrutPsemjTWIvH0xcGpy4wqMw2mMg7/RlgGvrv1jNzJFPSLpgFtQ0Hyg1Ho+mlv95Wz919VjbHaL84=
    password: AgA+ZvCXFiotje8/CDp/afirhu5Php2/AwWc9JimAFlDRokyrW2T8JR/dcr1ZlZBzsTePqhkgPAAqHGKXSVcqosPfhdPdK6eg247k1WARRBF1cvqaqtt/c9dhGtBfwbhSE4gSrmKpB3mGOLCtunSKh0DCC++xy1bvKCLhjjsgBqNLQf9lj0TKyFKCLGL/XYL8tVUBaU66F4u+c56wyj2nvuXTMOd8MA8E89ELhflPxk1Mhpyq5nT0CXHDaSOW4yd31WmIObZ7YvNEFwZLqShKwCMsZ08iqVSLX3QeDLKYTJMLwk0P/dwttK79244UN6IfSVw9OTuWuZof3kRoTAAFvgjd9LRaPI2NgWwTFWAn1Yp2Ac4Qs2Bix4JbXF7uxF44mazXu+VXk1TSiskwCl4YONaoIkOP1u5cpJJsnaAUltq61D5ASXWIZkr6YqkB7n2Pd0wolF20h4ou22vEo7265uAh0XxlfG+CYi92duaY2yEKPq/5YoLLt8UMfaBZepPMx3UDzKrlP+sCJk1CnrE4fAT2K8Nr7eaZ6fhaTCIFi4sLIW7zSxIUalqJsGQX+fhn8eJeaAdYbXwm3kYLXO1udWN5jahbHKggsspzb2J0z8FEi5ocFqYbhAdVUe4D7jeEGJIgFIrmHByRAi3OLTgmbRhYVr6Xeep7kSw02IjCU4yNaUg42ibrTspsRwUo+ABzy1dygzIpk8OQ5mf+t+Z
    user: AgBIgWlBeSMnbbRrns39ISECNjO3jgCeFZaQ13f7Po/LSG/r4lW3pTmY6ALHZ7lAzuXEG4k+FsGsFoGYxyKJ+1ZvyhZA+rPjhhcsm34jToWH4UtlKToiu4PyQsKVhL9M/pY6RyF7fGt4hgJMikjVm9PPFn1fxpXetNYLupqLUiSru4bg2T8tcpv6iEgaNfLSAH4ePANwopysHZndHUKPfra2DVal5luX3zxrMYO4HkUNimLTxigH+VIRKrfxfxk87H6/qVS98W4j3etgSZdSN+N4EKbymEobDc63muwFpLwrGaNUCS6zeKva8tpxXHGeKE6uKb+ilXo+9pnevAwtxRNAVZMQg+rS6z/ImFaZqdu1pxVa5/UYxpLWRc5ozrUTwSw27UJHSzyc7D4KLxIpNONtN0wQhkr+7NwU5GtBvpmOK+ToPyynrwhvnwyaqyqwTabjiEdJSDgbKtLsSYLSrvClNugnQ7qrdkYigq2lFAxubtTNeL/UdNN15R0aKXZq27KohcvjJSvcF+hWNhVgIOPG4np4CIBZMsh0mno1lZ1UFl+hm9V6y+H1c6j9A2/jcjgVOq38tp6QTgIutaDOhkOCyxyL+f9bbjhIfQjxrKOWtZYnlkg6uQ6IILP0mu/cFAfh+5uoBoLBpO2YtddoyvV1L74TQblgVfGN2vlNI302iSLkPWt9WqR4MeQAjmFLqQ/wtI4=
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: n8n
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "backups"
