---

apiVersion: vertica.com/v1beta1
kind: VerticaDB
metadata:
  name: verticadb-bar
  namespace: verticadb-operator
spec:
  # image: 'vertica/vertica-k8s:12.0.1-0-minimal'
  image: 'vertica/vertica-k8s:12.0.2-0-minimal'
  # image: 'vertica/vertica-k8s:12.0.3-0-minimal'
  # image: 'vertica/vertica-k8s:12.0.4-0-nokeys'

  labels:
    purpose: analytics
    owner: team-foo

  # communal:
  #   endpoint: 'https://s3.amazonaws.com'
  #   path: "s3://bucket-name"

  kSafety: "1"

  # licenseSecret: license

  subclusters:
    # default
    - name: default_subcluster
      size: 2

      # resources:
      #   requests:
      #     cpu: 0.1
      #     memory: 128Mi
      #   limit:
      #     cpu: 0.5
      #     memory: 512Mi

      # nodeSelector:
      #   disktype: ssd
      #   region: us-east

    # - name: my_subcluster
    #   size: 1
  sshSecret: vertica-ssh-secret
