---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: karma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://wiremind.github.io/wiremind-helm-charts
    chart: karma
    targetRevision: 2.1.3

    helm:
      values: |
        # https://github.com/wiremind/wiremind-helm-charts/blob/main/charts/karma/values.yaml

        deployment:
          annotations:
            configmap.reloader.stakater.com/reload: "karma"

        configMap:
          enabled: true

          ## karma compatible YAML configuration
          rawConfig:
            listen:
              address: "0.0.0.0"
              port: 8080
              prefix: /

            alertmanager:
              interval: 30s
              servers:
                - name: alertmanager-agrrh-com
                  uri: https://alertmanager.agrrh.com

            annotations:
              default:
                hidden: false
              hidden:
                - help
              visible: []

            filters:
              default:
                - "@receiver=by-cluster-service"

            labels:
              color:
                static:
                  - job
                unique:
                  - cluster
                  - instance
                  - "@receiver"
              keep: []
              strip: []

            log:
              config: false
              level: info

            # jira:
            #   - regex: DEVOPS-[0-9]+
            #     uri: https://jira.example.com

            receivers:
              keep: []
              strip: []

            # sentry:
            #   private: secret

            # public: 123456789

  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
